INSERT INTO avalsoft.pais(codigo, nombre, estado) 
VALUES ('AD','Andorra',TRUE),
		('AE','Emiratos Árabes Unidos',TRUE),
		('AF','Afganistán',TRUE),
		('AG','Antigua y Barbuda',TRUE),
		('AI','Anguila',TRUE),
		('AL','Albania',TRUE),
		('AM','Armenia',TRUE),
		('AN','Antillas Neerlandesas',TRUE),
		('AO','Angola',TRUE),
		('AQ','Antártida',TRUE),
		('AR','Argentina',TRUE),
		('AS','Samoa Americana',TRUE),
		('AT','Austria',TRUE),
		('AU','Australia',TRUE),
		('AW','Aruba',TRUE),
		('AX','Islas Áland',TRUE),
		('AZ','Azerbaiyán',TRUE),
		('BA','Bosnia y Herzegovina',TRUE),
		('BB','Barbados',TRUE),
		('BD','Bangladesh',TRUE),
		('BE','Bélgica',TRUE),
		('BF','Burkina Faso',TRUE),
		('BG','Bulgaria',TRUE),
		('BH','Bahréin',TRUE),
		('BI','Burundi',TRUE),
		('BJ','Benin',TRUE),
		('BL','San Bartolomé',TRUE),
		('BM','Bermudas',TRUE),
		('BN','Brunéi',TRUE),
		('BO','Bolivia',TRUE),
		('BR','Brasil',TRUE),
		('BS','Bahamas',TRUE),
		('BT','Bhután',TRUE),
		('BV','Isla Bouvet',TRUE),
		('BW','Botsuana',TRUE),
		('BY','Belarús',TRUE),
		('BZ','Belice',TRUE),
		('CA','Canadá',TRUE),
		('CC','Islas Cocos',TRUE),
		('CF','República Centro-Africana',TRUE),
		('CG','Congo',TRUE),
		('CH','Suiza',TRUE),
		('CI','Costa de Marfil',TRUE),
		('CK','Islas Cook',TRUE),
		('CL','Chile',TRUE),
		('CM','Camerún',TRUE),
		('CN','China',TRUE),
		('CO','Colombia',TRUE),
		('CR','Costa Rica',TRUE),
		('CU','Cuba',TRUE),
		('CV','Cabo Verde',TRUE),
		('CX','Islas Christmas',TRUE),
		('CY','Chipre',TRUE),
		('CZ','República Checa',TRUE),
		('DE','Alemania',TRUE),
		('DJ','Yibuti',TRUE),
		('DK','Dinamarca',TRUE),
		('DM','Domínica',TRUE),
		('DO','República Dominicana',TRUE),
		('DZ','Argel',TRUE),
		('EC','Ecuador',TRUE),
		('EE','Estonia',TRUE),
		('EG','Egipto',TRUE),
		('EH','Sahara Occidental',TRUE),
		('ER','Eritrea',TRUE),
		('ES','España',TRUE),
		('ET','Etiopía',TRUE),
		('FI','Finlandia',TRUE),
		('FJ','Fiji',TRUE),
		('FK','Islas Malvinas',TRUE),
		('FM','Micronesia',TRUE),
		('FO','Islas Faroe',TRUE),
		('FR','Francia',TRUE),
		('GA','Gabón',TRUE),
		('GB','Reino Unido',TRUE),
		('GD','Granada',TRUE),
		('GE','Georgia',TRUE),
		('GF','Guayana Francesa',TRUE),
		('GG','Guernsey',TRUE),
		('GH','Ghana',TRUE),
		('GI','Gibraltar',TRUE),
		('GL','Groenlandia',TRUE),
		('GM','Gambia',TRUE),
		('GN','Guinea',TRUE),
		('GP','Guadalupe',TRUE),
		('GQ','Guinea Ecuatorial',TRUE),
		('GR','Grecia',TRUE),
		('GS','Georgia del Sur e Islas Sandwich del Sur',TRUE),
		('GT','Guatemala',TRUE),
		('GU','Guam',TRUE),
		('GW','Guinea-Bissau',TRUE),
		('GY','Guayana',TRUE),
		('HK','Hong Kong',TRUE),
		('HM','Islas Heard y McDonald',TRUE),
		('HN','Honduras',TRUE),
		('HR','Croacia',TRUE),
		('HT','Haití',TRUE),
		('HU','Hungría',TRUE),
		('ID','Indonesia',TRUE),
		('IE','Irlanda',TRUE),
		('IL','Israel',TRUE),
		('IM','Isla de Man',TRUE),
		('IN','India',TRUE),
		('IO','Territorio Británico del Océano Índico',TRUE),
		('IQ','Irak',TRUE),
		('IR','Irán',TRUE),
		('IS','Islandia',TRUE),
		('IT','Italia',TRUE),
		('JE','Jersey',TRUE),
		('JM','Jamaica',TRUE),
		('JO','Jordania',TRUE),
		('JP','Japón',TRUE),
		('KE','Kenia',TRUE),
		('KG','Kirguistán',TRUE),
		('KH','Camboya',TRUE),
		('KI','Kiribati',TRUE),
		('KM','Comoros',TRUE),
		('KN','San Cristóbal y Nieves',TRUE),
		('KP','Corea del Norte',TRUE),
		('KR','Corea del Sur',TRUE),
		('KW','Kuwait',TRUE),
		('KY','Islas Caimán',TRUE),
		('KZ','Kazajstán',TRUE),
		('LA','Laos',TRUE),
		('LB','Líbano',TRUE),
		('LC','Santa Lucía',TRUE),
		('LI','Liechtenstein',TRUE),
		('LK','Sri Lanka',TRUE),
		('LR','Liberia',TRUE),
		('LS','Lesotho',TRUE),
		('LT','Lituania',TRUE),
		('LU','Luxemburgo',TRUE),
		('LV','Letonia',TRUE),
		('LY','Libia',TRUE),
		('MA','Marruecos',TRUE),
		('MC','Mónaco',TRUE),
		('MD','Moldova',TRUE),
		('ME','Montenegro',TRUE),
		('MG','Madagascar',TRUE),
		('MH','Islas Marshall',TRUE),
		('MK','Macedonia',TRUE),
		('ML','Mali',TRUE),
		('MM','Myanmar',TRUE),
		('MN','Mongolia',TRUE),
		('MO','Macao',TRUE),
		('MQ','Martinica',TRUE),
		('MR','Mauritania',TRUE),
		('MS','Montserrat',TRUE),
		('MT','Malta',TRUE),
		('MU','Mauricio',TRUE),
		('MV','Maldivas',TRUE),
		('MW','Malawi',TRUE),
		('MX','México',TRUE),
		('MY','Malasia',TRUE),
		('MZ','Mozambique',TRUE),
		('NA','Namibia',TRUE),
		('NC','Nueva Caledonia',TRUE),
		('NE','Níger',TRUE),
		('NF','Islas Norkfolk',TRUE),
		('NG','Nigeria',TRUE),
		('NI','Nicaragua',TRUE),
		('NL','Países Bajos',TRUE),
		('NO','Noruega',TRUE),
		('NP','Nepal',TRUE),
		('NR','Nauru',TRUE),
		('NU','Niue',TRUE),
		('NZ','Nueva Zelanda',TRUE),
		('OM','Omán',TRUE),
		('PA','Panamá',TRUE),
		('PE','Perú',TRUE),
		('PF','Polinesia Francesa',TRUE),
		('PG','Papúa Nueva Guinea',TRUE),
		('PH','Filipinas',TRUE),
		('PK','Pakistán',TRUE),
		('PL','Polonia',TRUE),
		('PM','San Pedro y Miquelón',TRUE),
		('PN','Islas Pitcairn',TRUE),
		('PR','Puerto Rico',TRUE),
		('PS','Palestina',TRUE),
		('PT','Portugal',TRUE),
		('PW','Islas Palaos',TRUE),
		('PY','Paraguay',TRUE),
		('QA','Qatar',TRUE),
		('RE','Reunión',TRUE),
		('RO','Rumanía',TRUE),
		('RS','Serbia y Montenegro',TRUE),
		('RU','Rusia',TRUE),
		('RW','Ruanda',TRUE),
		('SA','Arabia Saudita',TRUE),
		('SB','Islas Solomón',TRUE),
		('SC','Seychelles',TRUE),
		('SD','Sudán',TRUE),
		('SE','Suecia',TRUE),
		('SG','Singapur',TRUE),
		('SH','Santa Elena',TRUE),
		('SI','Eslovenia',TRUE),
		('SJ','Islas Svalbard y Jan Mayen',TRUE),
		('SK','Eslovaquia',TRUE),
		('SL','Sierra Leona',TRUE),
		('SM','San Marino',TRUE),
		('SN','Senegal',TRUE),
		('SO','Somalia',TRUE),
		('SR','Surinam',TRUE),
		('ST','Santo Tomé y Príncipe',TRUE),
		('SV','El Salvador',TRUE),
		('SY','Siria',TRUE),
		('SZ','Suazilandia',TRUE),
		('TC','Islas Turcas y Caicos',TRUE),
		('TD','Chad',TRUE),
		('TF','Territorios Australes Franceses',TRUE),
		('TG','Togo',TRUE),
		('TH','Tailandia',TRUE),
		('TH','Tanzania',TRUE),
		('TJ','Tayikistán',TRUE),
		('TK','Tokelau',TRUE),
		('TL','Timor-Leste',TRUE),
		('TM','Turkmenistán',TRUE),
		('TN','Túnez',TRUE),
		('TO','Tonga',TRUE),
		('TR','Turquía',TRUE),
		('TT','Trinidad y Tobago',TRUE),
		('TV','Tuvalu',TRUE),
		('TW','Taiwán',TRUE),
		('UA','Ucrania',TRUE),
		('UG','Uganda',TRUE),
		('US','Estados Unidos de América',TRUE),
		('UY','Uruguay',TRUE),
		('UZ','Uzbekistán',TRUE),
		('VA','Ciudad del Vaticano',TRUE),
		('VC','San Vicente y las Granadinas',TRUE),
		('VE','Venezuela',TRUE),
		('VG','Islas Vírgenes Británicas',TRUE),
		('VI','Islas Vírgenes de los Estados Unidos de América',TRUE),
		('VN','Vietnam',	TRUE),
		('VU','Vanuatu',	TRUE),
		('WF','Wallis y Futuna',TRUE),
		('WS','Samoa',TRUE),
		('YE','Yemen',TRUE),
		('YT','Mayotte',TRUE),
		('ZA','Sudáfrica',TRUE);


INSERT INTO avalsoft.departamento(codigo, nombre, estado, pais_id)
VALUES ('AN', 'ANTIOQUIA',TRUE, 48),
		('AT', 'ATLANTICO',TRUE, 48),
		('GV', 'GUAVIARE',TRUE, 48),
		('BL', 'BOLIVAR',TRUE, 48),
		('BY', 'BOYACA',TRUE, 48),
		('CL', 'CALDAS',TRUE, 48),
		('CQ', 'CAQUETA',TRUE, 48),
		('CU', 'CAUCA',TRUE, 48),
		('CS', 'CESAR',TRUE, 48),
		('CD', 'CORDOBA',TRUE, 48),
		('CN', 'CUNDINAMARCA',TRUE, 48),
		('CH', 'CHOCO',TRUE, 48),
		('HU', 'HUILA',TRUE, 48),
		('LG', 'LA GUAJIRA',TRUE, 48),
		('MG', 'MAGDALENA',TRUE, 48),
		('MT', 'META',TRUE, 48),
		('NR', 'NARIÑO',TRUE, 48),
		('NS', 'N. DE SANTANDER',TRUE, 48),
		('QD', 'QUINDIO',TRUE, 48),
		('RS', 'RISARALDA',TRUE, 48),
		('ST', 'SANTANDER',TRUE, 48),
		('SC', 'SUCRE',TRUE, 48),
		('TL', 'TOLIMA',TRUE, 48),
		('VC', 'VALLE DEL CAUCA',TRUE, 48),
		('AU', 'ARAUCA',TRUE, 48),
		('CR', 'CASANARE',TRUE, 48),
		('PT', 'PUTUMAYO',TRUE, 48),
		('SA', 'SAN ANDRES',TRUE, 48),
		('AZ', 'AMAZONAS',TRUE, 48),
		('GI', 'GUAINIA',TRUE, 48),
		('VP', 'VAUPES',TRUE, 48),
		('VH', 'VICHADA',TRUE, 48);
		
INSERT INTO avalsoft.ciudad(departamento_id, nombre, estado)
VALUES
(1, 'MEDELLIN', TRUE),
(1, 'ABEJORRAL', TRUE),
(1, 'ABRIAQUI', TRUE),
(1, 'ALEJANDRIA', TRUE),
(1, 'AMAGA', TRUE),
(1, 'AMALFI', TRUE),
(1, 'ANDES', TRUE),
(1, 'ANGELOPOLIS', TRUE),
(1, 'ANGOSTURA', TRUE),
(1, 'ANORI', TRUE),
(1, 'SANTAFE DE ANTIOQUIA', TRUE),
(1, 'ANZA', TRUE),
(1, 'APARTADO', TRUE),
(1, 'ARBOLETES', TRUE),
(1, 'ARGELIA', TRUE),
(1, 'ARMENIA', TRUE),
(1, 'BARBOSA', TRUE),
(1, 'BELMIRA', TRUE),
(1, 'BELLO', TRUE),
(1, 'BETANIA', TRUE),
(1, 'BETULIA', TRUE),
(1, 'CIUDAD BOLIVAR', TRUE),
(1, 'BRICEÑO', TRUE),
(1, 'BURITICA', TRUE),
(1, 'CACERES', TRUE),
(1, 'CAICEDO', TRUE),
(1, 'CALDAS', TRUE),
(1, 'CAMPAMENTO', TRUE),
(1, 'CAÑASGORDAS', TRUE),
(1, 'CARACOLI', TRUE),
(1, 'CARAMANTA', TRUE),
(1, 'CAREPA', TRUE),
(1, 'EL CARMEN DE VIBORAL', TRUE),
(1, 'CAROLINA', TRUE),
(1, 'CAUCASIA', TRUE),
(1, 'CHIGORODO', TRUE),
(1, 'CISNEROS', TRUE),
(1, 'COCORNA', TRUE),
(1, 'CONCEPCION', TRUE),
(1, 'CONCORDIA', TRUE),
(1, 'COPACABANA', TRUE),
(1, 'DABEIBA', TRUE),
(1, 'DON MATIAS', TRUE),
(1, 'EBEJICO', TRUE),
(1, 'EL BAGRE', TRUE),
(1, 'ENTRERRIOS', TRUE),
(1, 'ENVIGADO', TRUE),
(1, 'FREDONIA', TRUE),
(1, 'FRONTINO', TRUE),
(1, 'GIRALDO', TRUE),
(1, 'GIRARDOTA', TRUE),
(1, 'GOMEZ PLATA', TRUE),
(1, 'GRANADA', TRUE),
(1, 'GUADALUPE', TRUE),
(1, 'GUARNE', TRUE),
(1, 'GUATAPE', TRUE),
(1, 'HELICONIA', TRUE),
(1, 'HISPANIA', TRUE),
(1, 'ITAGUI', TRUE),
(1, 'ITUANGO', TRUE),
(1, 'JARDIN', TRUE),
(1, 'JERICO', TRUE),
(1, 'LA CEJA', TRUE),
(1, 'LA ESTRELLA', TRUE),
(1, 'LA PINTADA', TRUE),
(1, 'LA UNION', TRUE),
(1, 'LIBORINA', TRUE),
(1, 'MACEO', TRUE),
(1, 'MARINILLA', TRUE),
(1, 'MONTEBELLO', TRUE),
(1, 'MURINDO', TRUE),
(1, 'MUTATA', TRUE),
(1, 'NARIÑO', TRUE),
(1, 'NECOCLI', TRUE),
(1, 'NECHI', TRUE),
(1, 'OLAYA', TRUE),
(1, 'PEÐOL', TRUE),
(1, 'PEQUE', TRUE),
(1, 'PUEBLORRICO', TRUE),
(1, 'PUERTO BERRIO', TRUE),
(1, 'PUERTO NARE', TRUE),
(1, 'PUERTO TRIUNFO', TRUE),
(1, 'REMEDIOS', TRUE),
(1, 'RETIRO', TRUE),
(1, 'RIONEGRO', TRUE),
(1, 'SABANALARGA', TRUE),
(1, 'SABANETA', TRUE),
(1, 'SALGAR', TRUE),
(1, 'SAN ANDRES DE CUERQUIA', TRUE),
(1, 'SAN CARLOS', TRUE),
(1, 'SAN FRANCISCO', TRUE),
(1, 'SAN JERONIMO', TRUE),
(1, 'SAN JOSE DE LA MONTAÑA', TRUE),
(1, 'SAN JUAN DE URABA', TRUE),
(1, 'SAN LUIS', TRUE),
(1, 'SAN PEDRO', TRUE),
(1, 'SAN PEDRO DE URABA', TRUE),
(1, 'SAN RAFAEL', TRUE),
(1, 'SAN ROQUE', TRUE),
(1, 'SAN VICENTE', TRUE),
(1, 'SANTA BARBARA', TRUE),
(1, 'SANTA ROSA DE OSOS', TRUE),
(1, 'SANTO DOMINGO', TRUE),
(1, 'EL SANTUARIO', TRUE),
(1, 'SEGOVIA', TRUE),
(1, 'SONSON', TRUE),
(1, 'SOPETRAN', TRUE),
(1, 'TAMESIS', TRUE),
(1, 'TARAZA', TRUE),
(1, 'TARSO', TRUE),
(1, 'TITIRIBI', TRUE),
(1, 'TOLEDO', TRUE),
(1, 'TURBO', TRUE),
(1, 'URAMITA', TRUE),
(1, 'URRAO', TRUE),
(1, 'VALDIVIA', TRUE),
(1, 'VALPARAISO', TRUE),
(1, 'VEGACHI', TRUE),
(1, 'VENECIA', TRUE),
(1, 'VIGIA DEL FUERTE', TRUE),
(1, 'YALI', TRUE),
(1, 'YARUMAL', TRUE),
(1, 'YOLOMBO', TRUE),
(1, 'YONDO', TRUE),
(1, 'ZARAGOZA', TRUE),
(2, 'BARRANQUILLA', TRUE),
(2, 'BARANOA', TRUE),
(2, 'CAMPO DE LA CRUZ', TRUE),
(2, 'CANDELARIA', TRUE),
(2, 'GALAPA', TRUE),
(2, 'JUAN DE ACOSTA', TRUE),
(2, 'LURUACO', TRUE),
(2, 'MALAMBO', TRUE),
(2, 'MANATI', TRUE),
(2, 'PALMAR DE VARELA', TRUE),
(2, 'PIOJO', TRUE),
(2, 'POLONUEVO', TRUE),
(2, 'PONEDERA', TRUE),
(2, 'PUERTO COLOMBIA', TRUE),
(2, 'REPELON', TRUE),
(2, 'SABANAGRANDE', TRUE),
(2, 'SABANALARGA', TRUE),
(2, 'SANTA LUCIA', TRUE),
(2, 'SANTO TOMAS', TRUE),
(2, 'SOLEDAD', TRUE),
(2, 'SUAN', TRUE),
(2, 'TUBARA', TRUE),
(2, 'USIACURI', TRUE),
(3, 'SAN JOSE DEL GUAVIARE', TRUE),
(3, 'CALAMAR', TRUE),
(3, 'EL RETORNO', TRUE),
(3, 'MIRAFLORES', TRUE),
(4, 'CARTAGENA', TRUE),
(4, 'ACHI', TRUE),
(4, 'ALTOS DEL ROSARIO', TRUE),
(4, 'ARENAL', TRUE),
(4, 'ARJONA', TRUE),
(4, 'ARROYOHONDO', TRUE),
(4, 'BARRANCO DE LOBA', TRUE),
(4, 'CALAMAR', TRUE),
(4, 'CANTAGALLO', TRUE),
(4, 'CICUCO', TRUE),
(4, 'CORDOBA', TRUE),
(4, 'CLEMENCIA', TRUE),
(4, 'EL CARMEN DE BOLIVAR', TRUE),
(4, 'EL GUAMO', TRUE),
(4, 'EL PEÑON', TRUE),
(4, 'HATILLO DE LOBA', TRUE),
(4, 'MAGANGUE', TRUE),
(4, 'MAHATES', TRUE),
(4, 'MARGARITA', TRUE),
(4, 'MARIA LA BAJA', TRUE),
(4, 'MONTECRISTO', TRUE),
(4, 'MOMPOS', TRUE),
(4, 'NOROSI', TRUE),
(4, 'MORALES', TRUE),
(4, 'PINILLOS', TRUE),
(4, 'REGIDOR', TRUE),
(4, 'RIO VIEJO', TRUE),
(4, 'SAN CRISTOBAL', TRUE),
(4, 'SAN ESTANISLAO', TRUE),
(4, 'SAN FERNANDO', TRUE),
(4, 'SAN JACINTO', TRUE),
(4, 'SAN JACINTO DEL CAUCA', TRUE),
(4, 'SAN JUAN NEPOMUCENO', TRUE),
(4, 'SAN MARTIN DE LOBA', TRUE),
(4, 'SAN PABLO', TRUE),
(4, 'SANTA CATALINA', TRUE),
(4, 'SANTA ROSA', TRUE),
(4, 'SANTA ROSA DEL SUR', TRUE),
(4, 'SIMITI', TRUE),
(4, 'SOPLAVIENTO', TRUE),
(4, 'TALAIGUA NUEVO', TRUE),
(4, 'TIQUISIO', TRUE),
(4, 'TURBACO', TRUE),
(4, 'TURBANA', TRUE),
(4, 'VILLANUEVA', TRUE),
(4, 'ZAMBRANO', TRUE),
(5, 'TUNJA', TRUE),
(5, 'ALMEIDA', TRUE),
(5, 'AQUITANIA', TRUE),
(5, 'ARCABUCO', TRUE),
(5, 'BELEN', TRUE),
(5, 'BERBEO', TRUE),
(5, 'BETEITIVA', TRUE),
(5, 'BOAVITA', TRUE),
(5, 'BOYACA', TRUE),
(5, 'BRICEÑO', TRUE),
(5, 'BUENAVISTA', TRUE),
(5, 'BUSBANZA', TRUE),
(5, 'CALDAS', TRUE),
(5, 'CAMPOHERMOSO', TRUE),
(5, 'CERINZA', TRUE),
(5, 'CHINAVITA', TRUE),
(5, 'CHIQUINQUIRA', TRUE),
(5, 'CHISCAS', TRUE),
(5, 'CHITA', TRUE),
(5, 'CHITARAQUE', TRUE),
(5, 'CHIVATA', TRUE),
(5, 'CIENEGA', TRUE),
(5, 'COMBITA', TRUE),
(5, 'COPER', TRUE),
(5, 'CORRALES', TRUE),
(5, 'COVARACHIA', TRUE),
(5, 'CUBARA', TRUE),
(5, 'CUCAITA', TRUE),
(5, 'CUITIVA', TRUE),
(5, 'CHIQUIZA', TRUE),
(5, 'CHIVOR', TRUE),
(5, 'DUITAMA', TRUE),
(5, 'EL COCUY', TRUE),
(5, 'EL ESPINO', TRUE),
(5, 'FIRAVITOBA', TRUE),
(5, 'FLORESTA', TRUE),
(5, 'GACHANTIVA', TRUE),
(5, 'GAMEZA', TRUE),
(5, 'GARAGOA', TRUE),
(5, 'GUACAMAYAS', TRUE),
(5, 'GUATEQUE', TRUE),
(5, 'GUAYATA', TRUE),
(5, 'GsICAN', TRUE),
(5, 'IZA', TRUE),
(5, 'JENESANO', TRUE),
(5, 'JERICO', TRUE),
(5, 'LABRANZAGRANDE', TRUE),
(5, 'LA CAPILLA', TRUE),
(5, 'LA VICTORIA', TRUE),
(5, 'LA UVITA', TRUE),
(5, 'VILLA DE LEYVA', TRUE),
(5, 'MACANAL', TRUE),
(5, 'MARIPI', TRUE),
(5, 'MIRAFLORES', TRUE),
(5, 'MONGUA', TRUE),
(5, 'MONGUI', TRUE),
(5, 'MONIQUIRA', TRUE),
(5, 'MOTAVITA', TRUE),
(5, 'MUZO', TRUE),
(5, 'NOBSA', TRUE),
(5, 'NUEVO COLON', TRUE),
(5, 'OICATA', TRUE),
(5, 'OTANCHE', TRUE),
(5, 'PACHAVITA', TRUE),
(5, 'PAEZ', TRUE),
(5, 'PAIPA', TRUE),
(5, 'PAJARITO', TRUE),
(5, 'PANQUEBA', TRUE),
(5, 'PAUNA', TRUE),
(5, 'PAYA', TRUE),
(5, 'PAZ DE RIO', TRUE),
(5, 'PESCA', TRUE),
(5, 'PISBA', TRUE),
(5, 'PUERTO BOYACA', TRUE),
(5, 'QUIPAMA', TRUE),
(5, 'RAMIRIQUI', TRUE),
(5, 'RAQUIRA', TRUE),
(5, 'RONDON', TRUE),
(5, 'SABOYA', TRUE),
(5, 'SACHICA', TRUE),
(5, 'SAMACA', TRUE),
(5, 'SAN EDUARDO', TRUE),
(5, 'SAN JOSE DE PARE', TRUE),
(5, 'SAN LUIS DE GACENO', TRUE),
(5, 'SAN MATEO', TRUE),
(5, 'SAN MIGUEL DE SEMA', TRUE),
(5, 'SAN PABLO DE BORBUR', TRUE),
(5, 'SANTANA', TRUE),
(5, 'SANTA MARIA', TRUE),
(5, 'SANTA ROSA DE VITERBO', TRUE),
(5, 'SANTA SOFIA', TRUE),
(5, 'SATIVANORTE', TRUE),
(5, 'SATIVASUR', TRUE),
(5, 'SIACHOQUE', TRUE),
(5, 'SOATA', TRUE),
(5, 'SOCOTA', TRUE),
(5, 'SOCHA', TRUE),
(5, 'SOGAMOSO', TRUE),
(5, 'SOMONDOCO', TRUE),
(5, 'SORA', TRUE),
(5, 'SOTAQUIRA', TRUE),
(5, 'SORACA', TRUE),
(5, 'SUSACON', TRUE),
(5, 'SUTAMARCHAN', TRUE),
(5, 'SUTATENZA', TRUE),
(5, 'TASCO', TRUE),
(5, 'TENZA', TRUE),
(5, 'TIBANA', TRUE),
(5, 'TIBASOSA', TRUE),
(5, 'TINJACA', TRUE),
(5, 'TIPACOQUE', TRUE),
(5, 'TOCA', TRUE),
(5, 'TOGsI', TRUE),
(5, 'TOPAGA', TRUE),
(5, 'TOTA', TRUE),
(5, 'TUNUNGUA', TRUE),
(5, 'TURMEQUE', TRUE),
(5, 'TUTA', TRUE),
(5, 'TUTAZA', TRUE),
(5, 'UMBITA', TRUE),
(5, 'VENTAQUEMADA', TRUE),
(5, 'VIRACACHA', TRUE),
(5, 'ZETAQUIRA', TRUE),
(6, 'MANIZALES', TRUE),
(6, 'AGUADAS', TRUE),
(6, 'ANSERMA', TRUE),
(6, 'ARANZAZU', TRUE),
(6, 'BELALCAZAR', TRUE),
(6, 'CHINCHINA', TRUE),
(6, 'FILADELFIA', TRUE),
(6, 'LA DORADA', TRUE),
(6, 'LA MERCED', TRUE),
(6, 'MANZANARES', TRUE),
(6, 'MARMATO', TRUE),
(6, 'MARQUETALIA', TRUE),
(6, 'MARULANDA', TRUE),
(6, 'NEIRA', TRUE),
(6, 'NORCASIA', TRUE),
(6, 'PACORA', TRUE),
(6, 'PALESTINA', TRUE),
(6, 'PENSILVANIA', TRUE),
(6, 'RIOSUCIO', TRUE),
(6, 'RISARALDA', TRUE),
(6, 'SALAMINA', TRUE),
(6, 'SAMANA', TRUE),
(6, 'SAN JOSE', TRUE),
(6, 'SUPIA', TRUE),
(6, 'VICTORIA', TRUE),
(6, 'VILLAMARIA', TRUE),
(6, 'VITERBO', TRUE),
(7, 'FLORENCIA', TRUE),
(7, 'ALBANIA', TRUE),
(7, 'BELEN DE LOS ANDAQUIES', TRUE),
(7, 'CARTAGENA DEL CHAIRA', TRUE),
(7, 'CURILLO', TRUE),
(7, 'EL DONCELLO', TRUE),
(7, 'EL PAUJIL', TRUE),
(7, 'LA MONTAÑITA', TRUE),
(7, 'MILAN', TRUE),
(7, 'MORELIA', TRUE),
(7, 'PUERTO RICO', TRUE),
(7, 'SAN JOSE DEL FRAGUA', TRUE),
(7, 'SAN VICENTE DEL CAGUAN', TRUE),
(7, 'SOLANO', TRUE),
(7, 'SOLITA', TRUE),
(7, 'VALPARAISO', TRUE),
(8, 'POPAYAN', TRUE),
(8, 'ALMAGUER', TRUE),
(8, 'ARGELIA', TRUE),
(8, 'BALBOA', TRUE),
(8, 'BOLIVAR', TRUE),
(8, 'BUENOS AIRES', TRUE),
(8, 'CAJIBIO', TRUE),
(8, 'CALDONO', TRUE),
(8, 'CALOTO', TRUE),
(8, 'CORINTO', TRUE),
(8, 'EL TAMBO', TRUE),
(8, 'FLORENCIA', TRUE),
(8, 'GUACHENE', TRUE),
(8, 'GUAPI', TRUE),
(8, 'INZA', TRUE),
(8, 'JAMBALO', TRUE),
(8, 'LA SIERRA', TRUE),
(8, 'LA VEGA', TRUE),
(8, 'LOPEZ', TRUE),
(8, 'MERCADERES', TRUE),
(8, 'MIRANDA', TRUE),
(8, 'MORALES', TRUE),
(8, 'PADILLA', TRUE),
(8, 'PAEZ', TRUE),
(8, 'PATIA', TRUE),
(8, 'PIAMONTE', TRUE),
(8, 'PIENDAMO', TRUE),
(8, 'PUERTO TEJADA', TRUE),
(8, 'PURACE', TRUE),
(8, 'ROSAS', TRUE),
(8, 'SAN SEBASTIAN', TRUE),
(8, 'SANTANDER DE QUILICHAO', TRUE),
(8, 'SANTA ROSA', TRUE),
(8, 'SILVIA', TRUE),
(8, 'SOTARA', TRUE),
(8, 'SUAREZ', TRUE),
(8, 'SUCRE', TRUE),
(8, 'TIMBIO', TRUE),
(8, 'TIMBIQUI', TRUE),
(8, 'TORIBIO', TRUE),
(8, 'TOTORO', TRUE),
(8, 'VILLA RICA', TRUE),
(9, 'VALLEDUPAR', TRUE),
(9, 'AGUACHICA', TRUE),
(9, 'AGUSTIN CODAZZI', TRUE),
(9, 'ASTREA', TRUE),
(9, 'BECERRIL', TRUE),
(9, 'BOSCONIA', TRUE),
(9, 'CHIMICHAGUA', TRUE),
(9, 'CHIRIGUANA', TRUE),
(9, 'CURUMANI', TRUE),
(9, 'EL COPEY', TRUE),
(9, 'EL PASO', TRUE),
(9, 'GAMARRA', TRUE),
(9, 'GONZALEZ', TRUE),
(9, 'LA GLORIA', TRUE),
(9, 'LA JAGUA DE IBIRICO', TRUE),
(9, 'MANAURE', TRUE),
(9, 'PAILITAS', TRUE),
(9, 'PELAYA', TRUE),
(9, 'PUEBLO BELLO', TRUE),
(9, 'RIO DE ORO', TRUE),
(9, 'LA PAZ', TRUE),
(9, 'SAN ALBERTO', TRUE),
(9, 'SAN DIEGO', TRUE),
(9, 'SAN MARTIN', TRUE),
(9, 'TAMALAMEQUE', TRUE),
(10, 'MONTERIA', TRUE),
(10, 'AYAPEL', TRUE),
(10, 'BUENAVISTA', TRUE),
(10, 'CANALETE', TRUE),
(10, 'CERETE', TRUE),
(10, 'CHIMA', TRUE),
(10, 'CHINU', TRUE),
(10, 'CIENAGA DE ORO', TRUE),
(10, 'COTORRA', TRUE),
(10, 'LA APARTADA', TRUE),
(10, 'LORICA', TRUE),
(10, 'LOS CORDOBAS', TRUE),
(10, 'MOMIL', TRUE),
(10, 'MONTELIBANO', TRUE),
(10, 'MOÑITOS', TRUE),
(10, 'PLANETA RICA', TRUE),
(10, 'PUEBLO NUEVO', TRUE),
(10, 'PUERTO ESCONDIDO', TRUE),
(10, 'PUERTO LIBERTADOR', TRUE),
(10, 'PURISIMA', TRUE),
(10, 'SAHAGUN', TRUE),
(10, 'SAN ANDRES SOTAVENTO', TRUE),
(10, 'SAN ANTERO', TRUE),
(10, 'SAN BERNARDO DEL VIENTO', TRUE),
(10, 'SAN CARLOS', TRUE),
(10, 'SAN PELAYO', TRUE),
(10, 'TIERRALTA', TRUE),
(10, 'VALENCIA', TRUE),
(11, 'AGUA DE DIOS', TRUE),
(11, 'ALBAN', TRUE),
(11, 'ANAPOIMA', TRUE),
(11, 'ANOLAIMA', TRUE),
(11, 'ARBELAEZ', TRUE),
(11, 'BELTRAN', TRUE),
(11, 'BITUIMA', TRUE),
(11, 'BOJACA', TRUE),
(11, 'CABRERA', TRUE),
(11, 'CACHIPAY', TRUE),
(11, 'CAJICA', TRUE),
(11, 'CAPARRAPI', TRUE),
(11, 'CAQUEZA', TRUE),
(11, 'CARMEN DE CARUPA', TRUE),
(11, 'CHAGUANI', TRUE),
(11, 'CHIA', TRUE),
(11, 'CHIPAQUE', TRUE),
(11, 'CHOACHI', TRUE),
(11, 'CHOCONTA', TRUE),
(11, 'COGUA', TRUE),
(11, 'COTA', TRUE),
(11, 'CUCUNUBA', TRUE),
(11, 'EL COLEGIO', TRUE),
(11, 'EL PEÑON', TRUE),
(11, 'EL ROSAL', TRUE),
(11, 'FACATATIVA', TRUE),
(11, 'FOMEQUE', TRUE),
(11, 'FOSCA', TRUE),
(11, 'FUNZA', TRUE),
(11, 'FUQUENE', TRUE),
(11, 'FUSAGASUGA', TRUE),
(11, 'GACHALA', TRUE),
(11, 'GACHANCIPA', TRUE),
(11, 'GACHETA', TRUE),
(11, 'GAMA', TRUE),
(11, 'GIRARDOT', TRUE),
(11, 'GRANADA', TRUE),
(11, 'GUACHETA', TRUE),
(11, 'GUADUAS', TRUE),
(11, 'GUASCA', TRUE),
(11, 'GUATAQUI', TRUE),
(11, 'GUATAVITA', TRUE),
(11, 'GUAYABAL DE SIQUIMA', TRUE),
(11, 'GUAYABETAL', TRUE),
(11, 'GUTIERREZ', TRUE),
(11, 'JERUSALEN', TRUE),
(11, 'JUNIN', TRUE),
(11, 'LA CALERA', TRUE),
(11, 'LA MESA', TRUE),
(11, 'LA PALMA', TRUE),
(11, 'LA PEÑA', TRUE),
(11, 'LA VEGA', TRUE),
(11, 'LENGUAZAQUE', TRUE),
(11, 'MACHETA', TRUE),
(11, 'MADRID', TRUE),
(11, 'MANTA', TRUE),
(11, 'MEDINA', TRUE),
(11, 'MOSQUERA', TRUE),
(11, 'NARIÑO', TRUE),
(11, 'NEMOCON', TRUE),
(11, 'NILO', TRUE),
(11, 'NIMAIMA', TRUE),
(11, 'NOCAIMA', TRUE),
(11, 'VENECIA', TRUE),
(11, 'PACHO', TRUE),
(11, 'PAIME', TRUE),
(11, 'PANDI', TRUE),
(11, 'PARATEBUENO', TRUE),
(11, 'PASCA', TRUE),
(11, 'PUERTO SALGAR', TRUE),
(11, 'PULI', TRUE),
(11, 'QUEBRADANEGRA', TRUE),
(11, 'QUETAME', TRUE),
(11, 'QUIPILE', TRUE),
(11, 'APULO', TRUE),
(11, 'RICAURTE', TRUE),
(11, 'SAN ANTONIO DEL TEQUENDAMA', TRUE),
(11, 'SAN BERNARDO', TRUE),
(11, 'SAN CAYETANO', TRUE),
(11, 'SAN FRANCISCO', TRUE),
(11, 'SAN JUAN DE RIO SECO', TRUE),
(11, 'SASAIMA', TRUE),
(11, 'SESQUILE', TRUE),
(11, 'SIBATE', TRUE),
(11, 'SILVANIA', TRUE),
(11, 'SIMIJACA', TRUE),
(11, 'SOACHA', TRUE),
(11, 'SOPO', TRUE),
(11, 'SUBACHOQUE', TRUE),
(11, 'SUESCA', TRUE),
(11, 'SUPATA', TRUE),
(11, 'SUSA', TRUE),
(11, 'SUTATAUSA', TRUE),
(11, 'TABIO', TRUE),
(11, 'TAUSA', TRUE),
(11, 'TENA', TRUE),
(11, 'TENJO', TRUE),
(11, 'TIBACUY', TRUE),
(11, 'TIBIRITA', TRUE),
(11, 'TOCAIMA', TRUE),
(11, 'TOCANCIPA', TRUE),
(11, 'TOPAIPI', TRUE),
(11, 'UBALA', TRUE),
(11, 'UBAQUE', TRUE),
(11, 'VILLA DE SAN DIEGO DE UBATE', TRUE),
(11, 'UNE', TRUE),
(11, 'UTICA', TRUE),
(11, 'VERGARA', TRUE),
(11, 'VIANI', TRUE),
(11, 'VILLAGOMEZ', TRUE),
(11, 'VILLAPINZON', TRUE),
(11, 'VILLETA', TRUE),
(11, 'VIOTA', TRUE),
(11, 'YACOPI', TRUE),
(11, 'ZIPACON', TRUE),
(11, 'ZIPAQUIRA', TRUE),
(12, 'QUIBDO', TRUE),
(12, 'ACANDI', TRUE),
(12, 'ALTO BAUDO', TRUE),
(12, 'ATRATO', TRUE),
(12, 'BAGADO', TRUE),
(12, 'BAHIA SOLANO', TRUE),
(12, 'BAJO BAUDO', TRUE),
(12, 'BOJAYA', TRUE),
(12, 'EL CANTON DEL SAN PABLO', TRUE),
(12, 'CARMEN DEL DARIEN', TRUE),
(12, 'CERTEGUI', TRUE),
(12, 'CONDOTO', TRUE),
(12, 'EL CARMEN DE ATRATO', TRUE),
(12, 'EL LITORAL DEL SAN JUAN', TRUE),
(12, 'ISTMINA', TRUE),
(12, 'JURADO', TRUE),
(12, 'LLORO', TRUE),
(12, 'MEDIO ATRATO', TRUE),
(12, 'MEDIO BAUDO', TRUE),
(12, 'MEDIO SAN JUAN', TRUE),
(12, 'NOVITA', TRUE),
(12, 'NUQUI', TRUE),
(12, 'RIO IRO', TRUE),
(12, 'RIO QUITO', TRUE),
(12, 'RIOSUCIO', TRUE),
(12, 'SAN JOSE DEL PALMAR', TRUE),
(12, 'SIPI', TRUE),
(12, 'TADO', TRUE),
(12, 'UNGUIA', TRUE),
(12, 'UNION PANAMERICANA', TRUE),
(13, 'NEIVA', TRUE),
(13, 'ACEVEDO', TRUE),
(13, 'AGRADO', TRUE),
(13, 'AIPE', TRUE),
(13, 'ALGECIRAS', TRUE),
(13, 'ALTAMIRA', TRUE),
(13, 'BARAYA', TRUE),
(13, 'CAMPOALEGRE', TRUE),
(13, 'COLOMBIA', TRUE),
(13, 'ELIAS', TRUE),
(13, 'GARZON', TRUE),
(13, 'GIGANTE', TRUE),
(13, 'GUADALUPE', TRUE),
(13, 'HOBO', TRUE),
(13, 'IQUIRA', TRUE),
(13, 'ISNOS', TRUE),
(13, 'LA ARGENTINA', TRUE),
(13, 'LA PLATA', TRUE),
(13, 'NATAGA', TRUE),
(13, 'OPORAPA', TRUE),
(13, 'PAICOL', TRUE),
(13, 'PALERMO', TRUE),
(13, 'PALESTINA', TRUE),
(13, 'PITAL', TRUE),
(13, 'PITALITO', TRUE),
(13, 'RIVERA', TRUE),
(13, 'SALADOBLANCO', TRUE),
(13, 'SAN AGUSTIN', TRUE),
(13, 'SANTA MARIA', TRUE),
(13, 'SUAZA', TRUE),
(13, 'TARQUI', TRUE),
(13, 'TESALIA', TRUE),
(13, 'TELLO', TRUE),
(13, 'TERUEL', TRUE),
(13, 'TIMANA', TRUE),
(13, 'VILLAVIEJA', TRUE),
(13, 'YAGUARA', TRUE),
(14, 'RIOHACHA', TRUE),
(14, 'ALBANIA', TRUE),
(14, 'BARRANCAS', TRUE),
(14, 'DIBULLA', TRUE),
(14, 'DISTRACCION', TRUE),
(14, 'EL MOLINO', TRUE),
(14, 'FONSECA', TRUE),
(14, 'HATONUEVO', TRUE),
(14, 'LA JAGUA DEL PILAR', TRUE),
(14, 'MAICAO', TRUE),
(14, 'MANAURE', TRUE),
(14, 'SAN JUAN DEL CESAR', TRUE),
(14, 'URIBIA', TRUE),
(14, 'URUMITA', TRUE),
(14, 'VILLANUEVA', TRUE),
(15, 'SANTA MARTA', TRUE),
(15, 'ALGARROBO', TRUE),
(15, 'ARACATACA', TRUE),
(15, 'ARIGUANI', TRUE),
(15, 'CERRO SAN ANTONIO', TRUE),
(15, 'CHIBOLO', TRUE),
(15, 'CIENAGA', TRUE),
(15, 'CONCORDIA', TRUE),
(15, 'EL BANCO', TRUE),
(15, 'EL PIÑON', TRUE),
(15, 'EL RETEN', TRUE),
(15, 'FUNDACION', TRUE),
(15, 'GUAMAL', TRUE),
(15, 'NUEVA GRANADA', TRUE),
(15, 'PEDRAZA', TRUE),
(15, 'PIJIÑO DEL CARMEN', TRUE),
(15, 'PIVIJAY', TRUE),
(15, 'PLATO', TRUE),
(15, 'PUEBLOVIEJO', TRUE),
(15, 'REMOLINO', TRUE),
(15, 'SABANAS DE SAN ANGEL', TRUE),
(15, 'SALAMINA', TRUE),
(15, 'SAN SEBASTIAN DE BUENAVISTA', TRUE),
(15, 'SAN ZENON', TRUE),
(15, 'SANTA ANA', TRUE),
(15, 'SANTA BARBARA DE PINTO', TRUE),
(15, 'SITIONUEVO', TRUE),
(15, 'TENERIFE', TRUE),
(15, 'ZAPAYAN', TRUE),
(15, 'ZONA BANANERA', TRUE),
(16, 'VILLAVICENCIO', TRUE),
(16, 'ACACIAS', TRUE),
(16, 'BARRANCA DE UPIA', TRUE),
(16, 'CABUYARO', TRUE),
(16, 'CASTILLA LA NUEVA', TRUE),
(16, 'CUBARRAL', TRUE),
(16, 'CUMARAL', TRUE),
(16, 'EL CALVARIO', TRUE),
(16, 'EL CASTILLO', TRUE),
(16, 'EL DORADO', TRUE),
(16, 'FUENTE DE ORO', TRUE),
(16, 'GRANADA', TRUE),
(16, 'GUAMAL', TRUE),
(16, 'MAPIRIPAN', TRUE),
(16, 'MESETAS', TRUE),
(16, 'LA MACARENA', TRUE),
(16, 'URIBE', TRUE),
(16, 'LEJANIAS', TRUE),
(16, 'PUERTO CONCORDIA', TRUE),
(16, 'PUERTO GAITAN', TRUE),
(16, 'PUERTO LOPEZ', TRUE),
(16, 'PUERTO LLERAS', TRUE),
(16, 'PUERTO RICO', TRUE),
(16, 'RESTREPO', TRUE),
(16, 'SAN CARLOS DE GUAROA', TRUE),
(16, 'SAN JUAN DE ARAMA', TRUE),
(16, 'SAN JUANITO', TRUE),
(16, 'SAN MARTIN', TRUE),
(16, 'VISTAHERMOSA', TRUE),
(17, 'PASTO', TRUE),
(17, 'ALBAN', TRUE),
(17, 'ALDANA', TRUE),
(17, 'ANCUYA', TRUE),
(17, 'ARBOLEDA', TRUE),
(17, 'BARBACOAS', TRUE),
(17, 'BELEN', TRUE),
(17, 'BUESACO', TRUE),
(17, 'COLON', TRUE),
(17, 'CONSACA', TRUE),
(17, 'CONTADERO', TRUE),
(17, 'CORDOBA', TRUE),
(17, 'CUASPUD', TRUE),
(17, 'CUMBAL', TRUE),
(17, 'CUMBITARA', TRUE),
(17, 'CHACHAGsI', TRUE),
(17, 'EL CHARCO', TRUE),
(17, 'EL PEÑOL', TRUE),
(17, 'EL ROSARIO', TRUE),
(17, 'EL TABLON DE GOMEZ', TRUE),
(17, 'EL TAMBO', TRUE),
(17, 'FUNES', TRUE),
(17, 'GUACHUCAL', TRUE),
(17, 'GUAITARILLA', TRUE),
(17, 'GUALMATAN', TRUE),
(17, 'ILES', TRUE),
(17, 'IMUES', TRUE),
(17, 'IPIALES', TRUE),
(17, 'LA CRUZ', TRUE),
(17, 'LA FLORIDA', TRUE),
(17, 'LA LLANADA', TRUE),
(17, 'LA TOLA', TRUE),
(17, 'LA UNION', TRUE),
(17, 'LEIVA', TRUE),
(17, 'LINARES', TRUE),
(17, 'LOS ANDES', TRUE),
(17, 'MAGsI', TRUE),
(17, 'MALLAMA', TRUE),
(17, 'MOSQUERA', TRUE),
(17, '17', TRUE),
(17, 'OLAYA HERRERA', TRUE),
(17, 'OSPINA', TRUE),
(17, 'FRANCISCO PIZARRO', TRUE),
(17, 'POLICARPA', TRUE),
(17, 'POTOSI', TRUE),
(17, 'PROVIDENCIA', TRUE),
(17, 'PUERRES', TRUE),
(17, 'PUPIALES', TRUE),
(17, 'RICAURTE', TRUE),
(17, 'ROBERTO PAYAN', TRUE),
(17, 'SAMANIEGO', TRUE),
(17, 'SANDONA', TRUE),
(17, 'SAN BERNARDO', TRUE),
(17, 'SAN LORENZO', TRUE),
(17, 'SAN PABLO', TRUE),
(17, 'SAN PEDRO DE CARTAGO', TRUE),
(17, 'SANTA BARBARA', TRUE),
(17, 'SANTACRUZ', TRUE),
(17, 'SAPUYES', TRUE),
(17, 'TAMINANGO', TRUE),
(17, 'TANGUA', TRUE),
(17, 'SAN ANDRES DE TUMACO', TRUE),
(17, 'TUQUERRES', TRUE),
(17, 'YACUANQUER', TRUE),
(18, 'CUCUTA', TRUE),
(18, 'ABREGO', TRUE),
(18, 'ARBOLEDAS', TRUE),
(18, 'BOCHALEMA', TRUE),
(18, 'BUCARASICA', TRUE),
(18, 'CACOTA', TRUE),
(18, 'CACHIRA', TRUE),
(18, 'CHINACOTA', TRUE),
(18, 'CHITAGA', TRUE),
(18, 'CONVENCION', TRUE),
(18, 'CUCUTILLA', TRUE),
(18, 'DURANIA', TRUE),
(18, 'EL CARMEN', TRUE),
(18, 'EL TARRA', TRUE),
(18, 'EL ZULIA', TRUE),
(18, 'GRAMALOTE', TRUE),
(18, 'HACARI', TRUE),
(18, 'HERRAN', TRUE),
(18, 'LABATECA', TRUE),
(18, 'LA ESPERANZA', TRUE),
(18, 'LA PLAYA', TRUE),
(18, 'LOS PATIOS', TRUE),
(18, 'LOURDES', TRUE),
(18, 'MUTISCUA', TRUE),
(18, 'OCAÑA', TRUE),
(18, 'PAMPLONA', TRUE),
(18, 'PAMPLONITA', TRUE),
(18, 'PUERTO SANTANDER', TRUE),
(18, 'RAGONVALIA', TRUE),
(18, 'SALAZAR', TRUE),
(18, 'SAN CALIXTO', TRUE),
(18, 'SAN CAYETANO', TRUE),
(18, 'SANTIAGO', TRUE),
(18, 'SARDINATA', TRUE),
(18, 'SILOS', TRUE),
(18, 'TEORAMA', TRUE),
(18, 'TIBU', TRUE),
(18, 'TOLEDO', TRUE),
(18, 'VILLA CARO', TRUE),
(18, 'VILLA DEL ROSARIO', TRUE),
(19, 'ARMENIA', TRUE),
(19, 'BUENAVISTA', TRUE),
(19, 'CALARCA', TRUE),
(19, 'CIRCASIA', TRUE),
(19, 'CORDOBA', TRUE),
(19, 'FILANDIA', TRUE),
(19, 'GENOVA', TRUE),
(19, 'LA TEBAIDA', TRUE),
(19, 'MONTENEGRO', TRUE),
(19, 'PIJAO', TRUE),
(19, 'QUIMBAYA', TRUE),
(19, 'SALENTO', TRUE),
(20, 'PEREIRA', TRUE),
(20, 'APIA', TRUE),
(20, 'BALBOA', TRUE),
(20, 'BELEN DE UMBRIA', TRUE),
(20, 'DOSQUEBRADAS', TRUE),
(20, 'GUATICA', TRUE),
(20, 'LA CELIA', TRUE),
(20, 'LA VIRGINIA', TRUE),
(20, 'MARSELLA', TRUE),
(20, 'MISTRATO', TRUE),
(20, 'PUEBLO RICO', TRUE),
(20, 'QUINCHIA', TRUE),
(20, 'SANTA ROSA DE CABAL', TRUE),
(20, 'SANTUARIO', TRUE),
(21, 'BUCARAMANGA', TRUE),
(21, 'AGUADA', TRUE),
(21, 'ALBANIA', TRUE),
(21, 'ARATOCA', TRUE),
(21, 'BARBOSA', TRUE),
(21, 'BARICHARA', TRUE),
(21, 'BARRANCABERMEJA', TRUE),
(21, 'BETULIA', TRUE),
(21, 'BOLIVAR', TRUE),
(21, 'CABRERA', TRUE),
(21, 'CALIFORNIA', TRUE),
(21, 'CAPITANEJO', TRUE),
(21, 'CARCASI', TRUE),
(21, 'CEPITA', TRUE),
(21, 'CERRITO', TRUE),
(21, 'CHARALA', TRUE),
(21, 'CHARTA', TRUE),
(21, 'CHIMA', TRUE),
(21, 'CHIPATA', TRUE),
(21, 'CIMITARRA', TRUE),
(21, 'CONCEPCION', TRUE),
(21, 'CONFINES', TRUE),
(21, 'CONTRATACION', TRUE),
(21, 'COROMORO', TRUE),
(21, 'CURITI', TRUE),
(21, 'EL CARMEN DE CHUCURI', TRUE),
(21, 'EL GUACAMAYO', TRUE),
(21, 'EL PEÑON', TRUE),
(21, 'EL PLAYON', TRUE),
(21, 'ENCINO', TRUE),
(21, 'ENCISO', TRUE),
(21, 'FLORIAN', TRUE),
(21, 'FLORIDABLANCA', TRUE),
(21, 'GALAN', TRUE),
(21, 'GAMBITA', TRUE),
(21, 'GIRON', TRUE),
(21, 'GUACA', TRUE),
(21, 'GUADALUPE', TRUE),
(21, 'GUAPOTA', TRUE),
(21, 'GUAVATA', TRUE),
(21, 'GsEPSA', TRUE),
(21, 'HATO', TRUE),
(21, 'JESUS MARIA', TRUE),
(21, 'JORDAN', TRUE),
(21, 'LA BELLEZA', TRUE),
(21, 'LANDAZURI', TRUE),
(21, 'LA PAZ', TRUE),
(21, 'LEBRIJA', TRUE),
(21, 'LOS SANTOS', TRUE),
(21, 'MACARAVITA', TRUE),
(21, 'MALAGA', TRUE),
(21, 'MATANZA', TRUE),
(21, 'MOGOTES', TRUE),
(21, 'MOLAGAVITA', TRUE),
(21, 'OCAMONTE', TRUE),
(21, 'OIBA', TRUE),
(21, 'ONZAGA', TRUE),
(21, 'PALMAR', TRUE),
(21, 'PALMAS DEL SOCORRO', TRUE),
(21, 'PARAMO', TRUE),
(21, 'PIEDECUESTA', TRUE),
(21, 'PINCHOTE', TRUE),
(21, 'PUENTE NACIONAL', TRUE),
(21, 'PUERTO PARRA', TRUE),
(21, 'PUERTO WILCHES', TRUE),
(21, 'RIONEGRO', TRUE),
(21, 'SABANA DE TORRES', TRUE),
(21, 'SAN ANDRES', TRUE),
(21, 'SAN BENITO', TRUE),
(21, 'SAN GIL', TRUE),
(21, 'SAN JOAQUIN', TRUE),
(21, 'SAN JOSE DE MIRANDA', TRUE),
(21, 'SAN MIGUEL', TRUE),
(21, 'SAN VICENTE DE CHUCURI', TRUE),
(21, 'SANTA BARBARA', TRUE),
(21, 'SANTA HELENA DEL OPON', TRUE),
(21, 'SIMACOTA', TRUE),
(21, 'SOCORRO', TRUE),
(21, 'SUAITA', TRUE),
(21, 'SUCRE', TRUE),
(21, 'SURATA', TRUE),
(21, 'TONA', TRUE),
(21, 'VALLE DE SAN JOSE', TRUE),
(21, 'VELEZ', TRUE),
(21, 'VETAS', TRUE),
(21, 'VILLANUEVA', TRUE),
(21, 'ZAPATOCA', TRUE),
(22, 'SINCELEJO', TRUE),
(22, 'BUENAVISTA', TRUE),
(22, 'CAIMITO', TRUE),
(22, 'COLOSO', TRUE),
(22, 'COROZAL', TRUE),
(22, 'COVEÑAS', TRUE),
(22, 'CHALAN', TRUE),
(22, 'EL ROBLE', TRUE),
(22, 'GALERAS', TRUE),
(22, 'GUARANDA', TRUE),
(22, 'LA UNION', TRUE),
(22, 'LOS PALMITOS', TRUE),
(22, 'MAJAGUAL', TRUE),
(22, 'MORROA', TRUE),
(22, 'OVEJAS', TRUE),
(22, 'PALMITO', TRUE),
(22, 'SAMPUES', TRUE),
(22, 'SAN BENITO ABAD', TRUE),
(22, 'SAN JUAN DE BETULIA', TRUE),
(22, 'SAN MARCOS', TRUE),
(22, 'SAN ONOFRE', TRUE),
(22, 'SAN PEDRO', TRUE),
(22, 'SAN LUIS DE SINCE', TRUE),
(22, 'SUCRE', TRUE),
(22, 'SANTIAGO DE TOLU', TRUE),
(22, 'TOLU VIEJO', TRUE),
(23, 'IBAGUE', TRUE),
(23, 'ALPUJARRA', TRUE),
(23, 'ALVARADO', TRUE),
(23, 'AMBALEMA', TRUE),
(23, 'ANZOATEGUI', TRUE),
(23, 'ARMERO', TRUE),
(23, 'ATACO', TRUE),
(23, 'CAJAMARCA', TRUE),
(23, 'CARMEN DE APICALA', TRUE),
(23, 'CASABIANCA', TRUE),
(23, 'CHAPARRAL', TRUE),
(23, 'COELLO', TRUE),
(23, 'COYAIMA', TRUE),
(23, 'CUNDAY', TRUE),
(23, 'DOLORES', TRUE),
(23, 'ESPINAL', TRUE),
(23, 'FALAN', TRUE),
(23, 'FLANDES', TRUE),
(23, 'FRESNO', TRUE),
(23, 'GUAMO', TRUE),
(23, 'HERVEO', TRUE),
(23, 'HONDA', TRUE),
(23, 'ICONONZO', TRUE),
(23, 'LERIDA', TRUE),
(23, 'LIBANO', TRUE),
(23, 'MARIQUITA', TRUE),
(23, 'MELGAR', TRUE),
(23, 'MURILLO', TRUE),
(23, 'NATAGAIMA', TRUE),
(23, 'ORTEGA', TRUE),
(23, 'PALOCABILDO', TRUE),
(23, 'PIEDRAS', TRUE),
(23, 'PLANADAS', TRUE),
(23, 'PRADO', TRUE),
(23, 'PURIFICACION', TRUE),
(23, 'RIOBLANCO', TRUE),
(23, 'RONCESVALLES', TRUE),
(23, 'ROVIRA', TRUE),
(23, 'SALDAÑA', TRUE),
(23, 'SAN ANTONIO', TRUE),
(23, 'SAN LUIS', TRUE),
(23, 'SANTA ISABEL', TRUE),
(23, 'SUAREZ', TRUE),
(23, 'VALLE DE SAN JUAN', TRUE),
(23, 'VENADILLO', TRUE),
(23, 'VILLAHERMOSA', TRUE),
(23, 'VILLARRICA', TRUE),
(24, 'CALI', TRUE),
(24, 'ALCALA', TRUE),
(24, 'ANDALUCIA', TRUE),
(24, 'ANSERMANUEVO', TRUE),
(24, 'ARGELIA', TRUE),
(24, 'BOLIVAR', TRUE),
(24, 'BUENAVENTURA', TRUE),
(24, 'GUADALAJARA DE BUGA', TRUE),
(24, 'BUGALAGRANDE', TRUE),
(24, 'CAICEDONIA', TRUE),
(24, 'CALIMA', TRUE),
(24, 'CANDELARIA', TRUE),
(24, 'CARTAGO', TRUE),
(24, 'DAGUA', TRUE),
(24, 'EL AGUILA', TRUE),
(24, 'EL CAIRO', TRUE),
(24, 'EL CERRITO', TRUE),
(24, 'EL DOVIO', TRUE),
(24, 'FLORIDA', TRUE),
(24, 'GINEBRA', TRUE),
(24, 'GUACARI', TRUE),
(24, 'JAMUNDI', TRUE),
(24, 'LA CUMBRE', TRUE),
(24, 'LA UNION', TRUE),
(24, 'LA VICTORIA', TRUE),
(24, 'OBANDO', TRUE),
(24, 'PALMIRA', TRUE),
(24, 'PRADERA', TRUE),
(24, 'RESTREPO', TRUE),
(24, 'RIOFRIO', TRUE),
(24, 'ROLDANILLO', TRUE),
(24, 'SAN PEDRO', TRUE),
(24, 'SEVILLA', TRUE),
(24, 'TORO', TRUE),
(24, 'TRUJILLO', TRUE),
(24, 'TULUA', TRUE),
(24, 'ULLOA', TRUE),
(24, 'VERSALLES', TRUE),
(24, 'VIJES', TRUE),
(24, 'YOTOCO', TRUE),
(24, 'YUMBO', TRUE),
(24, 'ZARZAL', TRUE),
(25, 'ARAUCA', TRUE),
(25, 'ARAUQUITA', TRUE),
(25, 'CRAVO NORTE', TRUE),
(25, 'FORTUL', TRUE),
(25, 'PUERTO RONDON', TRUE),
(25, 'SARAVENA', TRUE),
(25, 'TAME', TRUE),
(26, 'YOPAL', TRUE),
(26, 'AGUAZUL', TRUE),
(26, 'CHAMEZA', TRUE),
(26, 'HATO COROZAL', TRUE),
(26, 'LA SALINA', TRUE),
(26, 'MANI', TRUE),
(26, 'MONTERREY', TRUE),
(26, 'NUNCHIA', TRUE),
(26, 'OROCUE', TRUE),
(26, 'PAZ DE ARIPORO', TRUE),
(26, 'PORE', TRUE),
(26, 'RECETOR', TRUE),
(26, 'SABANALARGA', TRUE),
(26, 'SACAMA', TRUE),
(26, 'SAN LUIS DE PALENQUE', TRUE),
(26, 'TAMARA', TRUE),
(26, 'TAURAMENA', TRUE),
(26, 'TRINIDAD', TRUE),
(26, 'VILLANUEVA', TRUE),
(27, 'MOCOA', TRUE),
(27, 'COLON', TRUE),
(27, 'ORITO', TRUE),
(27, 'PUERTO ASIS', TRUE),
(27, 'PUERTO CAICEDO', TRUE),
(27, 'PUERTO GUZMAN', TRUE),
(27, 'LEGUIZAMO', TRUE),
(27, 'SIBUNDOY', TRUE),
(27, 'SAN FRANCISCO', TRUE),
(27, 'SAN MIGUEL', TRUE),
(27, 'SANTIAGO', TRUE),
(27, 'VALLE DEL GUAMUEZ', TRUE),
(27, 'VILLAGARZON', TRUE),
(28, 'SAN ANDRES', TRUE),
(28, 'PROVIDENCIA', TRUE),
(29, 'LETICIA', TRUE),
(29, 'EL ENCANTO', TRUE),
(29, 'LA CHORRERA', TRUE),
(29, 'LA PEDRERA', TRUE),
(29, 'LA VICTORIA', TRUE),
(29, 'MIRITI - PARANA', TRUE),
(29, 'PUERTO ALEGRIA', TRUE),
(29, 'PUERTO ARICA', TRUE),
(29, 'PUERTO NARIÑO', TRUE),
(29, 'PUERTO SANTANDER', TRUE),
(29, 'TARAPACA', TRUE),
(30, 'INIRIDA', TRUE),
(30, 'BARRANCO MINAS', TRUE),
(30, 'MAPIRIPANA', TRUE),
(30, 'SAN FELIPE', TRUE),
(30, 'PUERTO COLOMBIA', TRUE),
(30, 'LA GUADALUPE', TRUE),
(30, 'CACAHUAL', TRUE),
(30, 'PANA PANA', TRUE),
(30, 'MORICHAL', TRUE),
(31, 'MITU', TRUE),
(31, 'CARURU', TRUE),
(31, 'PACOA', TRUE),
(31, 'TARAIRA', TRUE),
(31, 'PAPUNAUA', TRUE),
(31, 'YAVARATE', TRUE),
(32, 'PUERTO CARREÑO', TRUE),
(32, 'LA PRIMAVERA', TRUE),
(32, 'SANTA ROSALIA', TRUE),
(32, 'CUMARIBO', TRUE),
(11, 'BOGOTA, D.C.', TRUE);

INSERT INTO avalsoft.empresa(
	tipo_identificacion, identificacion, nombre, description, estado, ciudad_id)
	VALUES ('NIT', '190988809-5', 'AVALUADORES SAS', 'MERA CALIDAD', true, 55),
	('CC', '1026147293', 'Jarrison Garcia', 'PARTICULAR', true, 13),
	('CC', '12345678', 'Hernan Hossa', 'PARTICULAR', true, 47),
	('NIT', '121212', 'Hernan Hossa', 'AVALSOFT', true, 12);

INSERT INTO avalsoft.rol( nombre, descripcion, estado)
VALUES ('Administrador', 'Administrador del sistema', true),
		('Empleado', 'Empleado de empresas de avaluos', true),
		('Cliente', 'Cliente de los empleados de los avaluadores', true);
		
INSERT INTO avalsoft.usuario(
	tipo_documento, identificacion, nombre, correo, direccion, telefono, 
	celular, contrasena, estado, lenguaje, profesion, rol_id, empresa_id)
VALUES ('CC', '77777777', 'Empleado 1', 'empleado1@gmail.com', 'direccion 1', 
		'5555555', '3114445555', '$2a$10$4ve60qpmDjYygoOpT5RoO.aSa9okecUo4jcAp5V.mMYvYGa0JUPXC', true, 'ES', 'Ingenebrio', 2, 1),
		('CC', '1026147293', 'Jarrison Garcia Particular', 'jarrison@gmail.com', 'direccion 2', 
		'1111111', '3117775555', '$2a$10$4ve60qpmDjYygoOpT5RoO.aSa9okecUo4jcAp5V.mMYvYGa0JUPXC', true,  'ES', 'Ingenebrio', 2, 2),
		('CC', '131313', 'avalsoft1', 'avalsoft1@gmail.com', 'direccion 1', 
		'4444444', '3125456677', '$2a$10$4ve60qpmDjYygoOpT5RoO.aSa9okecUo4jcAp5V.mMYvYGa0JUPXC', true, 'ES', 'Ingenebrio', 1, 4);


INSERT INTO avalsoft.licencia(
	nombre, ultimo_pago, fecha_expiracion, fecha_ultima_conn, ciudad_id, usuario_id)
	VALUES ('AVALSOFT', current_date, current_date+500, current_date, 1, 2),
	('AVALSOFT', current_date, current_date+500, current_date, 1, 1);

















