package co.com.avaluo.common;

public enum EnumListas {

	TIPOS_DOCUMENTO,
	LISTA_LICENCIAS,
	LISTA_IDIOMAS,
	LISTA_TIPO_PROPIEDAD_URBANO,
	LISTA_TIPO_PROPIEDAD_RURAL,
	LISTA_ESTRATOS,
	LISTA_TIPO_PROPIEDAD;
	
}
