package co.com.avaluo.model.entity;
// Generated 4/11/2018 09:11:06 AM by Hibernate Tools 4.0.1.Final

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CategoriasAvaluo generated by hbm2java
 */
@Entity
@Table(name = "categorias_avaluo", schema = "avalsoft")
public class CategoriasAvaluo implements java.io.Serializable {

	private int id;
	private String nombre;
	private List<Usuario> usuarios = new ArrayList<>();

	public CategoriasAvaluo() {
	}

	public CategoriasAvaluo(int id, String nombre) {
		this.id = id;
		this.nombre = nombre;
	}

	public CategoriasAvaluo(int id, String nombre, List<Usuario> usuarios) {
		this.id = id;
		this.nombre = nombre;
		this.usuarios = usuarios;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "nombre", nullable = false, length = 200)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "categoriasAvaluo")
	public List<Usuario> getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(List<Usuario> usuarios) {
		this.usuarios = usuarios;
	}

}
