package co.com.avaluo.model.entity;
// Generated 30/06/2018 02:39:09 PM by Hibernate Tools 5.3.0.Beta2

import java.util.HashSet;
import java.util.Set;

/**
 * Ciudad generated by hbm2java
 */
public class Ciudad implements java.io.Serializable {

	private int id;
	private Departamento departamento;
	private String nombre;
	private String codigo;
	private Boolean estado;
	private Set licencias = new HashSet(0);
	private Set propiedads = new HashSet(0);
	private Set empresas = new HashSet(0);

	public Ciudad() {
	}

	public Ciudad(int id, Departamento departamento) {
		this.id = id;
		this.departamento = departamento;
	}

	public Ciudad(int id, Departamento departamento, String nombre, String codigo, Boolean estado, Set licencias,
			Set propiedads, Set empresas) {
		this.id = id;
		this.departamento = departamento;
		this.nombre = nombre;
		this.codigo = codigo;
		this.estado = estado;
		this.licencias = licencias;
		this.propiedads = propiedads;
		this.empresas = empresas;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Departamento getDepartamento() {
		return this.departamento;
	}

	public void setDepartamento(Departamento departamento) {
		this.departamento = departamento;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	public Boolean getEstado() {
		return this.estado;
	}

	public void setEstado(Boolean estado) {
		this.estado = estado;
	}

	public Set getLicencias() {
		return this.licencias;
	}

	public void setLicencias(Set licencias) {
		this.licencias = licencias;
	}

	public Set getPropiedads() {
		return this.propiedads;
	}

	public void setPropiedads(Set propiedads) {
		this.propiedads = propiedads;
	}

	public Set getEmpresas() {
		return this.empresas;
	}

	public void setEmpresas(Set empresas) {
		this.empresas = empresas;
	}

}
