package co.com.avaluo.model.entity;
// Generated 30/06/2018 02:39:09 PM by Hibernate Tools 5.3.0.Beta2

/**
 * Contacto generated by hbm2java
 */
public class Contacto implements java.io.Serializable {

	private int id;
	private Usuario usuario;

	public Contacto() {
	}

	public Contacto(int id, Usuario usuario) {
		this.id = id;
		this.usuario = usuario;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

}
