package co.com.avaluo.model.entity;
// Generated 30/06/2018 02:39:09 PM by Hibernate Tools 5.3.0.Beta2

import java.math.BigDecimal;

/**
 * Cotizacion generated by hbm2java
 */
public class Cotizacion implements java.io.Serializable {

	private int id;
	private Empresa empresa;
	private Propiedad propiedad;
	private String tipo;
	private String nombre;
	private BigDecimal desde;
	private BigDecimal hasta;
	private BigDecimal delta;
	private BigDecimal factor;
	private BigDecimal base;
	private BigDecimal valor;
	private BigDecimal areaRango;
	private BigDecimal valorAreaRango;
	private BigDecimal residuo;
	private boolean estado;

	public Cotizacion() {
	}

	public Cotizacion(int id, Empresa empresa, Propiedad propiedad, boolean estado) {
		this.id = id;
		this.empresa = empresa;
		this.propiedad = propiedad;
		this.estado = estado;
	}

	public Cotizacion(int id, Empresa empresa, Propiedad propiedad, String tipo, String nombre, BigDecimal desde,
			BigDecimal hasta, BigDecimal delta, BigDecimal factor, BigDecimal base, BigDecimal valor,
			BigDecimal areaRango, BigDecimal valorAreaRango, BigDecimal residuo, boolean estado) {
		this.id = id;
		this.empresa = empresa;
		this.propiedad = propiedad;
		this.tipo = tipo;
		this.nombre = nombre;
		this.desde = desde;
		this.hasta = hasta;
		this.delta = delta;
		this.factor = factor;
		this.base = base;
		this.valor = valor;
		this.areaRango = areaRango;
		this.valorAreaRango = valorAreaRango;
		this.residuo = residuo;
		this.estado = estado;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Empresa getEmpresa() {
		return this.empresa;
	}

	public void setEmpresa(Empresa empresa) {
		this.empresa = empresa;
	}

	public Propiedad getPropiedad() {
		return this.propiedad;
	}

	public void setPropiedad(Propiedad propiedad) {
		this.propiedad = propiedad;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public BigDecimal getDesde() {
		return this.desde;
	}

	public void setDesde(BigDecimal desde) {
		this.desde = desde;
	}

	public BigDecimal getHasta() {
		return this.hasta;
	}

	public void setHasta(BigDecimal hasta) {
		this.hasta = hasta;
	}

	public BigDecimal getDelta() {
		return this.delta;
	}

	public void setDelta(BigDecimal delta) {
		this.delta = delta;
	}

	public BigDecimal getFactor() {
		return this.factor;
	}

	public void setFactor(BigDecimal factor) {
		this.factor = factor;
	}

	public BigDecimal getBase() {
		return this.base;
	}

	public void setBase(BigDecimal base) {
		this.base = base;
	}

	public BigDecimal getValor() {
		return this.valor;
	}

	public void setValor(BigDecimal valor) {
		this.valor = valor;
	}

	public BigDecimal getAreaRango() {
		return this.areaRango;
	}

	public void setAreaRango(BigDecimal areaRango) {
		this.areaRango = areaRango;
	}

	public BigDecimal getValorAreaRango() {
		return this.valorAreaRango;
	}

	public void setValorAreaRango(BigDecimal valorAreaRango) {
		this.valorAreaRango = valorAreaRango;
	}

	public BigDecimal getResiduo() {
		return this.residuo;
	}

	public void setResiduo(BigDecimal residuo) {
		this.residuo = residuo;
	}

	public boolean isEstado() {
		return this.estado;
	}

	public void setEstado(boolean estado) {
		this.estado = estado;
	}

}
