package co.com.avaluo.model.entity;
// Generated 30/06/2018 02:39:09 PM by Hibernate Tools 5.3.0.Beta2

import java.util.HashSet;
import java.util.Set;

/**
 * Departamento generated by hbm2java
 */
public class Departamento implements java.io.Serializable {

	private int id;
	private Pais pais;
	private String nombre;
	private String codigo;
	private boolean estado;
	private Set ciudads = new HashSet(0);

	public Departamento() {
	}

	public Departamento(int id, Pais pais, boolean estado) {
		this.id = id;
		this.pais = pais;
		this.estado = estado;
	}

	public Departamento(int id, Pais pais, String nombre, String codigo, boolean estado, Set ciudads) {
		this.id = id;
		this.pais = pais;
		this.nombre = nombre;
		this.codigo = codigo;
		this.estado = estado;
		this.ciudads = ciudads;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Pais getPais() {
		return this.pais;
	}

	public void setPais(Pais pais) {
		this.pais = pais;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	public boolean isEstado() {
		return this.estado;
	}

	public void setEstado(boolean estado) {
		this.estado = estado;
	}

	public Set getCiudads() {
		return this.ciudads;
	}

	public void setCiudads(Set ciudads) {
		this.ciudads = ciudads;
	}

}
