package co.com.avaluo.model.entity;
// Generated 20/07/2018 06:18:00 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DetalleCotizacion generated by hbm2java
 */
@Entity
@Table(name = "detalle_cotizacion", schema = "avalsoft")
public class DetalleCotizacion implements java.io.Serializable {

	private DetalleCotizacionId id;
	private Cotizacion cotizacion;
	private Propiedad propiedad;

	public DetalleCotizacion() {
	}

	public DetalleCotizacion(DetalleCotizacionId id, Cotizacion cotizacion, Propiedad propiedad) {
		this.id = id;
		this.cotizacion = cotizacion;
		this.propiedad = propiedad;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "cotizacionId", column = @Column(name = "cotizacion_id", nullable = false)),
			@AttributeOverride(name = "propiedadId", column = @Column(name = "propiedad_id", nullable = false)),
			@AttributeOverride(name = "valor", column = @Column(name = "valor", precision = 131089, scale = 0)) })
	public DetalleCotizacionId getId() {
		return this.id;
	}

	public void setId(DetalleCotizacionId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cotizacion_id", nullable = false, insertable = false, updatable = false)
	public Cotizacion getCotizacion() {
		return this.cotizacion;
	}

	public void setCotizacion(Cotizacion cotizacion) {
		this.cotizacion = cotizacion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "propiedad_id", nullable = false, insertable = false, updatable = false)
	public Propiedad getPropiedad() {
		return this.propiedad;
	}

	public void setPropiedad(Propiedad propiedad) {
		this.propiedad = propiedad;
	}

}
