package co.com.avaluo.model.entity;
// Generated 20/07/2018 06:18:00 PM by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DetalleCotizacionId generated by hbm2java
 */
@Embeddable
public class DetalleCotizacionId implements java.io.Serializable {

	private int cotizacionId;
	private int propiedadId;
	private BigDecimal valor;

	public DetalleCotizacionId() {
	}

	public DetalleCotizacionId(int cotizacionId, int propiedadId) {
		this.cotizacionId = cotizacionId;
		this.propiedadId = propiedadId;
	}

	public DetalleCotizacionId(int cotizacionId, int propiedadId, BigDecimal valor) {
		this.cotizacionId = cotizacionId;
		this.propiedadId = propiedadId;
		this.valor = valor;
	}

	@Column(name = "cotizacion_id", nullable = false)
	public int getCotizacionId() {
		return this.cotizacionId;
	}

	public void setCotizacionId(int cotizacionId) {
		this.cotizacionId = cotizacionId;
	}

	@Column(name = "propiedad_id", nullable = false)
	public int getPropiedadId() {
		return this.propiedadId;
	}

	public void setPropiedadId(int propiedadId) {
		this.propiedadId = propiedadId;
	}

	@Column(name = "valor", precision = 131089, scale = 0)
	public BigDecimal getValor() {
		return this.valor;
	}

	public void setValor(BigDecimal valor) {
		this.valor = valor;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DetalleCotizacionId))
			return false;
		DetalleCotizacionId castOther = (DetalleCotizacionId) other;

		return (this.getCotizacionId() == castOther.getCotizacionId())
				&& (this.getPropiedadId() == castOther.getPropiedadId())
				&& ((this.getValor() == castOther.getValor()) || (this.getValor() != null
						&& castOther.getValor() != null && this.getValor().equals(castOther.getValor())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCotizacionId();
		result = 37 * result + this.getPropiedadId();
		result = 37 * result + (getValor() == null ? 0 : this.getValor().hashCode());
		return result;
	}

}
