package co.com.avaluo.model.entity;
// Generated 2/07/2018 06:16:36 PM by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DetalleCotizacion generated by hbm2java
 */
@Entity
@Table(name = "detalle_cotizacion", schema = "avalsoft")
public class DetalleCotizacion implements java.io.Serializable {

	private int id;
	private int cotizacionId;
	private int propiedadId;
	private BigDecimal valor;

	public DetalleCotizacion() {
	}

	public DetalleCotizacion(int id, int cotizacionId, int propiedadId) {
		this.id = id;
		this.cotizacionId = cotizacionId;
		this.propiedadId = propiedadId;
	}

	public DetalleCotizacion(int id, int cotizacionId, int propiedadId, BigDecimal valor) {
		this.id = id;
		this.cotizacionId = cotizacionId;
		this.propiedadId = propiedadId;
		this.valor = valor;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "cotizacion_id", nullable = false)
	public int getCotizacionId() {
		return this.cotizacionId;
	}

	public void setCotizacionId(int cotizacionId) {
		this.cotizacionId = cotizacionId;
	}

	@Column(name = "propiedad_id", nullable = false)
	public int getPropiedadId() {
		return this.propiedadId;
	}

	public void setPropiedadId(int propiedadId) {
		this.propiedadId = propiedadId;
	}

	@Column(name = "valor", precision = 20, scale = 0)
	public BigDecimal getValor() {
		return this.valor;
	}

	public void setValor(BigDecimal valor) {
		this.valor = valor;
	}

}
