package co.com.avaluo.model.entity;
// Generated 10/06/2018 05:11:29 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DetailTable generated by hbm2java
 */
@Entity
@Table(name = "detail_table", schema = "avalsoft")
public class DetailTable implements java.io.Serializable {

	private int id;
	private Tables tables;
	private Long low;
	private Long up;
	private Double apply;

	public DetailTable() {
	}

	public DetailTable(int id) {
		this.id = id;
	}

	public DetailTable(int id, Tables tables, Long low, Long up, Double apply) {
		this.id = id;
		this.tables = tables;
		this.low = low;
		this.up = up;
		this.apply = apply;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_table")
	public Tables getTables() {
		return this.tables;
	}

	public void setTables(Tables tables) {
		this.tables = tables;
	}

	@Column(name = "low", precision = 10, scale = 0)
	public Long getLow() {
		return this.low;
	}

	public void setLow(Long low) {
		this.low = low;
	}

	@Column(name = "up", precision = 10, scale = 0)
	public Long getUp() {
		return this.up;
	}

	public void setUp(Long up) {
		this.up = up;
	}

	@Column(name = "apply", precision = 17, scale = 17)
	public Double getApply() {
		return this.apply;
	}

	public void setApply(Double apply) {
		this.apply = apply;
	}

}
