package co.com.avaluo.model.entity;
// Generated 9/08/2018 05:55:20 PM by Hibernate Tools 4.0.1.Final

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Direcciones generated by hbm2java
 */
@Entity
@Table(name = "direcciones", schema = "avalsoft")
public class Direcciones implements java.io.Serializable {

	private int id;
	private int propiedadId;
	private String tipoVia;
	private Integer numeroVia;
	private String letraVia;
	private String nombreVia;
	private String posicionVia;
	private Integer numeroInterseccion;
	private String letraInterseccion;
	private String posicionInterseccion;
	private String componenteInterseccion;
	private String tipoUbicacion;
	private Integer numeroUbicacion;
	private String lugarUbicacion;
	private Integer numeroLugar;
	private String apendice;
	private Integer aregioId;
	private String tipoUrbanizacion;
	private String descripUrbanizacion;
	private String tipoManzana;
	private String descripManzana;
	private String tipoPrefijo;
	private String tipoComponente;
	private String descripComponente;
	private List<Propiedad> propiedads = new ArrayList<Propiedad>(0);

	public Direcciones() {
	}

	public Direcciones(int id, int propiedadId) {
		this.id = id;
		this.propiedadId = propiedadId;
	}

	public Direcciones(int id, int propiedadId, String tipoVia, Integer numeroVia, String letraVia, String nombreVia,
			String posicionVia, Integer numeroInterseccion, String letraInterseccion, String posicionInterseccion,
			String componenteInterseccion, String tipoUbicacion, Integer numeroUbicacion, String lugarUbicacion,
			Integer numeroLugar, String apendice, Integer aregioId, String tipoUrbanizacion, String descripUrbanizacion,
			String tipoManzana, String descripManzana, String tipoPrefijo, String tipoComponente,
			String descripComponente, List<Propiedad> propiedads) {
		this.id = id;
		this.propiedadId = propiedadId;
		this.tipoVia = tipoVia;
		this.numeroVia = numeroVia;
		this.letraVia = letraVia;
		this.nombreVia = nombreVia;
		this.posicionVia = posicionVia;
		this.numeroInterseccion = numeroInterseccion;
		this.letraInterseccion = letraInterseccion;
		this.posicionInterseccion = posicionInterseccion;
		this.componenteInterseccion = componenteInterseccion;
		this.tipoUbicacion = tipoUbicacion;
		this.numeroUbicacion = numeroUbicacion;
		this.lugarUbicacion = lugarUbicacion;
		this.numeroLugar = numeroLugar;
		this.apendice = apendice;
		this.aregioId = aregioId;
		this.tipoUrbanizacion = tipoUrbanizacion;
		this.descripUrbanizacion = descripUrbanizacion;
		this.tipoManzana = tipoManzana;
		this.descripManzana = descripManzana;
		this.tipoPrefijo = tipoPrefijo;
		this.tipoComponente = tipoComponente;
		this.descripComponente = descripComponente;
		this.propiedads = propiedads;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "propiedad_id", nullable = false)
	public int getPropiedadId() {
		return this.propiedadId;
	}

	public void setPropiedadId(int propiedadId) {
		this.propiedadId = propiedadId;
	}

	@Column(name = "tipo_via", length = 20)
	public String getTipoVia() {
		return this.tipoVia;
	}

	public void setTipoVia(String tipoVia) {
		this.tipoVia = tipoVia;
	}

	@Column(name = "numero_via")
	public Integer getNumeroVia() {
		return this.numeroVia;
	}

	public void setNumeroVia(Integer numeroVia) {
		this.numeroVia = numeroVia;
	}

	@Column(name = "letra_via", length = 20)
	public String getLetraVia() {
		return this.letraVia;
	}

	public void setLetraVia(String letraVia) {
		this.letraVia = letraVia;
	}

	@Column(name = "nombre_via", length = 20)
	public String getNombreVia() {
		return this.nombreVia;
	}

	public void setNombreVia(String nombreVia) {
		this.nombreVia = nombreVia;
	}

	@Column(name = "posicion_via", length = 20)
	public String getPosicionVia() {
		return this.posicionVia;
	}

	public void setPosicionVia(String posicionVia) {
		this.posicionVia = posicionVia;
	}

	@Column(name = "numero_interseccion")
	public Integer getNumeroInterseccion() {
		return this.numeroInterseccion;
	}

	public void setNumeroInterseccion(Integer numeroInterseccion) {
		this.numeroInterseccion = numeroInterseccion;
	}

	@Column(name = "letra_interseccion", length = 20)
	public String getLetraInterseccion() {
		return this.letraInterseccion;
	}

	public void setLetraInterseccion(String letraInterseccion) {
		this.letraInterseccion = letraInterseccion;
	}

	@Column(name = "posicion_interseccion", length = 20)
	public String getPosicionInterseccion() {
		return this.posicionInterseccion;
	}

	public void setPosicionInterseccion(String posicionInterseccion) {
		this.posicionInterseccion = posicionInterseccion;
	}

	@Column(name = "componente_interseccion", length = 20)
	public String getComponenteInterseccion() {
		return this.componenteInterseccion;
	}

	public void setComponenteInterseccion(String componenteInterseccion) {
		this.componenteInterseccion = componenteInterseccion;
	}

	@Column(name = "tipo_ubicacion", length = 20)
	public String getTipoUbicacion() {
		return this.tipoUbicacion;
	}

	public void setTipoUbicacion(String tipoUbicacion) {
		this.tipoUbicacion = tipoUbicacion;
	}

	@Column(name = "numero_ubicacion")
	public Integer getNumeroUbicacion() {
		return this.numeroUbicacion;
	}

	public void setNumeroUbicacion(Integer numeroUbicacion) {
		this.numeroUbicacion = numeroUbicacion;
	}

	@Column(name = "lugar_ubicacion", length = 20)
	public String getLugarUbicacion() {
		return this.lugarUbicacion;
	}

	public void setLugarUbicacion(String lugarUbicacion) {
		this.lugarUbicacion = lugarUbicacion;
	}

	@Column(name = "numero_lugar")
	public Integer getNumeroLugar() {
		return this.numeroLugar;
	}

	public void setNumeroLugar(Integer numeroLugar) {
		this.numeroLugar = numeroLugar;
	}

	@Column(name = "apendice", length = 500)
	public String getApendice() {
		return this.apendice;
	}

	public void setApendice(String apendice) {
		this.apendice = apendice;
	}

	@Column(name = "aregio_id")
	public Integer getAregioId() {
		return this.aregioId;
	}

	public void setAregioId(Integer aregioId) {
		this.aregioId = aregioId;
	}

	@Column(name = "tipo_urbanizacion", length = 20)
	public String getTipoUrbanizacion() {
		return this.tipoUrbanizacion;
	}

	public void setTipoUrbanizacion(String tipoUrbanizacion) {
		this.tipoUrbanizacion = tipoUrbanizacion;
	}

	@Column(name = "descrip_urbanizacion", length = 20)
	public String getDescripUrbanizacion() {
		return this.descripUrbanizacion;
	}

	public void setDescripUrbanizacion(String descripUrbanizacion) {
		this.descripUrbanizacion = descripUrbanizacion;
	}

	@Column(name = "tipo_manzana", length = 20)
	public String getTipoManzana() {
		return this.tipoManzana;
	}

	public void setTipoManzana(String tipoManzana) {
		this.tipoManzana = tipoManzana;
	}

	@Column(name = "descrip_manzana", length = 20)
	public String getDescripManzana() {
		return this.descripManzana;
	}

	public void setDescripManzana(String descripManzana) {
		this.descripManzana = descripManzana;
	}

	@Column(name = "tipo_prefijo", length = 20)
	public String getTipoPrefijo() {
		return this.tipoPrefijo;
	}

	public void setTipoPrefijo(String tipoPrefijo) {
		this.tipoPrefijo = tipoPrefijo;
	}

	@Column(name = "tipo_componente", length = 20)
	public String getTipoComponente() {
		return this.tipoComponente;
	}

	public void setTipoComponente(String tipoComponente) {
		this.tipoComponente = tipoComponente;
	}

	@Column(name = "descrip_componente", length = 20)
	public String getDescripComponente() {
		return this.descripComponente;
	}

	public void setDescripComponente(String descripComponente) {
		this.descripComponente = descripComponente;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "direcciones")
	public List<Propiedad> getPropiedads() {
		return this.propiedads;
	}

	public void setPropiedads(List<Propiedad> propiedads) {
		this.propiedads = propiedads;
	}

}
