package co.com.avaluo.model.entity;
// Generated 4/11/2018 08:36:02 AM by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Documentos generated by hbm2java
 */
@Entity
@Table(name = "documentos", schema = "avalsoft")
public class Documentos implements java.io.Serializable {

	private int id;
	private Visitas visitas;
	private String latitud;
	private String longitud;
	private BigDecimal numeroEscritura;
	private Date fechaRegistro;
	private Integer numeroNotaria;
	private Integer circuitoNotarial;
	private String escrituraObjeto;
	private BigDecimal cedulaCatastral;
	private String entregaPlanos;
	private String licenciaConstrucc;
	private String afectaciones;
	private Short vetustez;
	private BigDecimal avaluoLote;
	private BigDecimal avaluoConstruccion;
	private BigDecimal registroCatastral;
	private String regimenPh;
	private String escrituraPublica;
	private Date fechaCatastral;
	private String certificadoLibertad;
	private String licenciaConstruccion;
	private String certificadoEstratificacion;
	private String plano;
	private String reglamentoPh;
	private String pagoZonasCom;

	public Documentos() {
	}

	public Documentos(int id, Visitas visitas) {
		this.id = id;
		this.visitas = visitas;
	}

	public Documentos(int id, Visitas visitas, String latitud, String longitud, BigDecimal numeroEscritura,
			Date fechaRegistro, Integer numeroNotaria, Integer circuitoNotarial, String escrituraObjeto,
			BigDecimal cedulaCatastral, String entregaPlanos, String licenciaConstrucc, String afectaciones,
			Short vetustez, BigDecimal avaluoLote, BigDecimal avaluoConstruccion, BigDecimal registroCatastral,
			String regimenPh, String escrituraPublica, Date fechaCatastral, String certificadoLibertad,
			String licenciaConstruccion, String certificadoEstratificacion, String plano, String reglamentoPh,
			String pagoZonasCom) {
		this.id = id;
		this.visitas = visitas;
		this.latitud = latitud;
		this.longitud = longitud;
		this.numeroEscritura = numeroEscritura;
		this.fechaRegistro = fechaRegistro;
		this.numeroNotaria = numeroNotaria;
		this.circuitoNotarial = circuitoNotarial;
		this.escrituraObjeto = escrituraObjeto;
		this.cedulaCatastral = cedulaCatastral;
		this.entregaPlanos = entregaPlanos;
		this.licenciaConstrucc = licenciaConstrucc;
		this.afectaciones = afectaciones;
		this.vetustez = vetustez;
		this.avaluoLote = avaluoLote;
		this.avaluoConstruccion = avaluoConstruccion;
		this.registroCatastral = registroCatastral;
		this.regimenPh = regimenPh;
		this.escrituraPublica = escrituraPublica;
		this.fechaCatastral = fechaCatastral;
		this.certificadoLibertad = certificadoLibertad;
		this.licenciaConstruccion = licenciaConstruccion;
		this.certificadoEstratificacion = certificadoEstratificacion;
		this.plano = plano;
		this.reglamentoPh = reglamentoPh;
		this.pagoZonasCom = pagoZonasCom;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "visitas_id", nullable = false)
	public Visitas getVisitas() {
		return this.visitas;
	}

	public void setVisitas(Visitas visitas) {
		this.visitas = visitas;
	}

	@Column(name = "latitud", length = 30)
	public String getLatitud() {
		return this.latitud;
	}

	public void setLatitud(String latitud) {
		this.latitud = latitud;
	}

	@Column(name = "longitud", length = 30)
	public String getLongitud() {
		return this.longitud;
	}

	public void setLongitud(String longitud) {
		this.longitud = longitud;
	}

	@Column(name = "numero_escritura", precision = 30, scale = 0)
	public BigDecimal getNumeroEscritura() {
		return this.numeroEscritura;
	}

	public void setNumeroEscritura(BigDecimal numeroEscritura) {
		this.numeroEscritura = numeroEscritura;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_registro", length = 13)
	public Date getFechaRegistro() {
		return this.fechaRegistro;
	}

	public void setFechaRegistro(Date fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}

	@Column(name = "numero_notaria", precision = 6, scale = 0)
	public Integer getNumeroNotaria() {
		return this.numeroNotaria;
	}

	public void setNumeroNotaria(Integer numeroNotaria) {
		this.numeroNotaria = numeroNotaria;
	}

	@Column(name = "circuito_notarial")
	public Integer getCircuitoNotarial() {
		return this.circuitoNotarial;
	}

	public void setCircuitoNotarial(Integer circuitoNotarial) {
		this.circuitoNotarial = circuitoNotarial;
	}

	@Column(name = "escritura_objeto")
	public String getEscrituraObjeto() {
		return this.escrituraObjeto;
	}

	public void setEscrituraObjeto(String escrituraObjeto) {
		this.escrituraObjeto = escrituraObjeto;
	}

	@Column(name = "cedula_catastral", precision = 30, scale = 0)
	public BigDecimal getCedulaCatastral() {
		return this.cedulaCatastral;
	}

	public void setCedulaCatastral(BigDecimal cedulaCatastral) {
		this.cedulaCatastral = cedulaCatastral;
	}

	@Column(name = "entrega_planos", length = 2)
	public String getEntregaPlanos() {
		return this.entregaPlanos;
	}

	public void setEntregaPlanos(String entregaPlanos) {
		this.entregaPlanos = entregaPlanos;
	}

	@Column(name = "licencia_construcc", length = 60)
	public String getLicenciaConstrucc() {
		return this.licenciaConstrucc;
	}

	public void setLicenciaConstrucc(String licenciaConstrucc) {
		this.licenciaConstrucc = licenciaConstrucc;
	}

	@Column(name = "afectaciones", length = 4000)
	public String getAfectaciones() {
		return this.afectaciones;
	}

	public void setAfectaciones(String afectaciones) {
		this.afectaciones = afectaciones;
	}

	@Column(name = "vetustez", precision = 4, scale = 0)
	public Short getVetustez() {
		return this.vetustez;
	}

	public void setVetustez(Short vetustez) {
		this.vetustez = vetustez;
	}

	@Column(name = "avaluo_lote", precision = 20, scale = 0)
	public BigDecimal getAvaluoLote() {
		return this.avaluoLote;
	}

	public void setAvaluoLote(BigDecimal avaluoLote) {
		this.avaluoLote = avaluoLote;
	}

	@Column(name = "avaluo_construccion", precision = 20, scale = 0)
	public BigDecimal getAvaluoConstruccion() {
		return this.avaluoConstruccion;
	}

	public void setAvaluoConstruccion(BigDecimal avaluoConstruccion) {
		this.avaluoConstruccion = avaluoConstruccion;
	}

	@Column(name = "registro_catastral", precision = 20, scale = 0)
	public BigDecimal getRegistroCatastral() {
		return this.registroCatastral;
	}

	public void setRegistroCatastral(BigDecimal registroCatastral) {
		this.registroCatastral = registroCatastral;
	}

	@Column(name = "regimen_ph", length = 2)
	public String getRegimenPh() {
		return this.regimenPh;
	}

	public void setRegimenPh(String regimenPh) {
		this.regimenPh = regimenPh;
	}

	@Column(name = "escritura_publica")
	public String getEscrituraPublica() {
		return this.escrituraPublica;
	}

	public void setEscrituraPublica(String escrituraPublica) {
		this.escrituraPublica = escrituraPublica;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_catastral", length = 13)
	public Date getFechaCatastral() {
		return this.fechaCatastral;
	}

	public void setFechaCatastral(Date fechaCatastral) {
		this.fechaCatastral = fechaCatastral;
	}

	@Column(name = "certificado-libertad", length = 2)
	public String getCertificadoLibertad() {
		return this.certificadoLibertad;
	}

	public void setCertificadoLibertad(String certificadoLibertad) {
		this.certificadoLibertad = certificadoLibertad;
	}

	@Column(name = "licencia_construccion", length = 2)
	public String getLicenciaConstruccion() {
		return this.licenciaConstruccion;
	}

	public void setLicenciaConstruccion(String licenciaConstruccion) {
		this.licenciaConstruccion = licenciaConstruccion;
	}

	@Column(name = "certificado_estratificacion", length = 2)
	public String getCertificadoEstratificacion() {
		return this.certificadoEstratificacion;
	}

	public void setCertificadoEstratificacion(String certificadoEstratificacion) {
		this.certificadoEstratificacion = certificadoEstratificacion;
	}

	@Column(name = "plano", length = 2)
	public String getPlano() {
		return this.plano;
	}

	public void setPlano(String plano) {
		this.plano = plano;
	}

	@Column(name = "reglamento_ph", length = 2)
	public String getReglamentoPh() {
		return this.reglamentoPh;
	}

	public void setReglamentoPh(String reglamentoPh) {
		this.reglamentoPh = reglamentoPh;
	}

	@Column(name = "pago_zonas_com", length = 2)
	public String getPagoZonasCom() {
		return this.pagoZonasCom;
	}

	public void setPagoZonasCom(String pagoZonasCom) {
		this.pagoZonasCom = pagoZonasCom;
	}

}
