package co.com.avaluo.model.entity;
// Generated 30/06/2018 02:39:09 PM by Hibernate Tools 5.3.0.Beta2

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Estrato generated by hbm2java
 */
public class Estrato implements java.io.Serializable {

	private int id;
	private Empresa empresa;
	private String nombre;
	private BigDecimal valor;
	private BigDecimal porcentaje;
	private Set propiedads = new HashSet(0);

	public Estrato() {
	}

	public Estrato(int id, Empresa empresa, BigDecimal valor, BigDecimal porcentaje) {
		this.id = id;
		this.empresa = empresa;
		this.valor = valor;
		this.porcentaje = porcentaje;
	}

	public Estrato(int id, Empresa empresa, String nombre, BigDecimal valor, BigDecimal porcentaje, Set propiedads) {
		this.id = id;
		this.empresa = empresa;
		this.nombre = nombre;
		this.valor = valor;
		this.porcentaje = porcentaje;
		this.propiedads = propiedads;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Empresa getEmpresa() {
		return this.empresa;
	}

	public void setEmpresa(Empresa empresa) {
		this.empresa = empresa;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public BigDecimal getValor() {
		return this.valor;
	}

	public void setValor(BigDecimal valor) {
		this.valor = valor;
	}

	public BigDecimal getPorcentaje() {
		return this.porcentaje;
	}

	public void setPorcentaje(BigDecimal porcentaje) {
		this.porcentaje = porcentaje;
	}

	public Set getPropiedads() {
		return this.propiedads;
	}

	public void setPropiedads(Set propiedads) {
		this.propiedads = propiedads;
	}

}
