package co.com.avaluo.model.entity;
// Generated 1/07/2018 10:51:15 AM by Hibernate Tools 4.0.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Licencia generated by hbm2java
 */
@Entity
@Table(name = "licencia", schema = "avalsoft")
public class Licencia implements java.io.Serializable {

	private int id;
	private Empresa empresa;
	private Ciudad ciudad;
	private String nombre;
	private Date ultimoPago;
	private Date fechaExpiracion;
	private Date fechaUltimaConn;

	public Licencia() {
	}

	public Licencia(int id, Empresa empresa, Ciudad ciudad) {
		this.id = id;
		this.empresa = empresa;
		this.ciudad = ciudad;
	}

	public Licencia(int id, Empresa empresa, Ciudad ciudad, String nombre, Date ultimoPago, Date fechaExpiracion,
			Date fechaUltimaConn) {
		this.id = id;
		this.empresa = empresa;
		this.ciudad = ciudad;
		this.nombre = nombre;
		this.ultimoPago = ultimoPago;
		this.fechaExpiracion = fechaExpiracion;
		this.fechaUltimaConn = fechaUltimaConn;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "empresa_id", nullable = false)
	public Empresa getEmpresa() {
		return this.empresa;
	}

	public void setEmpresa(Empresa empresa) {
		this.empresa = empresa;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ciudad_id", nullable = false)
	public Ciudad getCiudad() {
		return this.ciudad;
	}

	public void setCiudad(Ciudad ciudad) {
		this.ciudad = ciudad;
	}

	@Column(name = "nombre", length = 100)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ultimo_pago", length = 13)
	public Date getUltimoPago() {
		return this.ultimoPago;
	}

	public void setUltimoPago(Date ultimoPago) {
		this.ultimoPago = ultimoPago;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_expiracion", length = 13)
	public Date getFechaExpiracion() {
		return this.fechaExpiracion;
	}

	public void setFechaExpiracion(Date fechaExpiracion) {
		this.fechaExpiracion = fechaExpiracion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_ultima_conn", length = 13)
	public Date getFechaUltimaConn() {
		return this.fechaUltimaConn;
	}

	public void setFechaUltimaConn(Date fechaUltimaConn) {
		this.fechaUltimaConn = fechaUltimaConn;
	}

}
