package co.com.avaluo.model.entity;
// Generated 28/06/2018 07:22:07 PM by Hibernate Tools 5.3.0.Beta2

/**
 * MarketCategories generated by hbm2java
 */
public class MarketCategories implements java.io.Serializable {

	private int id;
	private Users users;
	private String name;
	private Double valor;
	private Double minimum;

	public MarketCategories() {
	}

	public MarketCategories(int id) {
		this.id = id;
	}

	public MarketCategories(int id, Users users, String name, Double valor, Double minimum) {
		this.id = id;
		this.users = users;
		this.name = name;
		this.valor = valor;
		this.minimum = minimum;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Double getValor() {
		return this.valor;
	}

	public void setValor(Double valor) {
		this.valor = valor;
	}

	public Double getMinimum() {
		return this.minimum;
	}

	public void setMinimum(Double minimum) {
		this.minimum = minimum;
	}

}
