package co.com.avaluo.model.entity;
// Generated 30/06/2018 02:39:09 PM by Hibernate Tools 5.3.0.Beta2

import java.util.HashSet;
import java.util.Set;

/**
 * Pais generated by hbm2java
 */
public class Pais implements java.io.Serializable {

	private int id;
	private String nombre;
	private String codigo;
	private boolean estado;
	private Set departamentos = new HashSet(0);

	public Pais() {
	}

	public Pais(int id, boolean estado) {
		this.id = id;
		this.estado = estado;
	}

	public Pais(int id, String nombre, String codigo, boolean estado, Set departamentos) {
		this.id = id;
		this.nombre = nombre;
		this.codigo = codigo;
		this.estado = estado;
		this.departamentos = departamentos;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	public boolean isEstado() {
		return this.estado;
	}

	public void setEstado(boolean estado) {
		this.estado = estado;
	}

	public Set getDepartamentos() {
		return this.departamentos;
	}

	public void setDepartamentos(Set departamentos) {
		this.departamentos = departamentos;
	}

}
