package co.com.avaluo.model.entity;
// Generated 10/06/2018 05:11:29 PM by Hibernate Tools 4.0.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ProfileAccount generated by hbm2java
 */
@Entity
@Table(name = "profile_account", schema = "avalsoft")
public class ProfileAccount implements java.io.Serializable {

	private int id;
	private String userName;
	private String idCart;
	private String profession;
	private String idProf;
	private String professionIi;
	private String idProfIi;
	private Date expirationDate;
	private String company;
	private String idCompany;
	private String email;
	private String contact;

	public ProfileAccount() {
	}

	public ProfileAccount(int id) {
		this.id = id;
	}

	public ProfileAccount(int id, String userName, String idCart, String profession, String idProf, String professionIi,
			String idProfIi, Date expirationDate, String company, String idCompany, String email, String contact) {
		this.id = id;
		this.userName = userName;
		this.idCart = idCart;
		this.profession = profession;
		this.idProf = idProf;
		this.professionIi = professionIi;
		this.idProfIi = idProfIi;
		this.expirationDate = expirationDate;
		this.company = company;
		this.idCompany = idCompany;
		this.email = email;
		this.contact = contact;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "user_name", length = 200)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "id_cart", length = 50)
	public String getIdCart() {
		return this.idCart;
	}

	public void setIdCart(String idCart) {
		this.idCart = idCart;
	}

	@Column(name = "profession", length = 200)
	public String getProfession() {
		return this.profession;
	}

	public void setProfession(String profession) {
		this.profession = profession;
	}

	@Column(name = "id_prof", length = 50)
	public String getIdProf() {
		return this.idProf;
	}

	public void setIdProf(String idProf) {
		this.idProf = idProf;
	}

	@Column(name = "profession_II", length = 200)
	public String getProfessionIi() {
		return this.professionIi;
	}

	public void setProfessionIi(String professionIi) {
		this.professionIi = professionIi;
	}

	@Column(name = "id_prof_II", length = 50)
	public String getIdProfIi() {
		return this.idProfIi;
	}

	public void setIdProfIi(String idProfIi) {
		this.idProfIi = idProfIi;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "expiration_date", length = 13)
	public Date getExpirationDate() {
		return this.expirationDate;
	}

	public void setExpirationDate(Date expirationDate) {
		this.expirationDate = expirationDate;
	}

	@Column(name = "company", length = 200)
	public String getCompany() {
		return this.company;
	}

	public void setCompany(String company) {
		this.company = company;
	}

	@Column(name = "id_company", length = 50)
	public String getIdCompany() {
		return this.idCompany;
	}

	public void setIdCompany(String idCompany) {
		this.idCompany = idCompany;
	}

	@Column(name = "email", length = 200)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "contact", length = 200)
	public String getContact() {
		return this.contact;
	}

	public void setContact(String contact) {
		this.contact = contact;
	}

}
