package co.com.avaluo.model.entity;
// Generated 17/06/2018 01:24:48 PM by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Properties generated by hbm2java
 */
@Entity
@Table(name = "properties", schema = "avalsoft")
public class Properties implements java.io.Serializable {

	private int id;
	private BigDecimal propertyType;
	private String zone;
	private String realEstateRegistration;
	private BigDecimal stratum;
	private String department;
	private String municipality;

	public Properties() {
	}

	public Properties(int id) {
		this.id = id;
	}

	public Properties(int id, BigDecimal propertyType, String zone, String realEstateRegistration, BigDecimal stratum,
			String department, String municipality) {
		this.id = id;
		this.propertyType = propertyType;
		this.zone = zone;
		this.realEstateRegistration = realEstateRegistration;
		this.stratum = stratum;
		this.department = department;
		this.municipality = municipality;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "property_type", precision = 20, scale = 0)
	public BigDecimal getPropertyType() {
		return this.propertyType;
	}

	public void setPropertyType(BigDecimal propertyType) {
		this.propertyType = propertyType;
	}

	@Column(name = "zone", length = 50)
	public String getZone() {
		return this.zone;
	}

	public void setZone(String zone) {
		this.zone = zone;
	}

	@Column(name = "real_estate_registration", length = 100)
	public String getRealEstateRegistration() {
		return this.realEstateRegistration;
	}

	public void setRealEstateRegistration(String realEstateRegistration) {
		this.realEstateRegistration = realEstateRegistration;
	}

	@Column(name = "stratum", precision = 20, scale = 0)
	public BigDecimal getStratum() {
		return this.stratum;
	}

	public void setStratum(BigDecimal stratum) {
		this.stratum = stratum;
	}

	@Column(name = "department", length = 200)
	public String getDepartment() {
		return this.department;
	}

	public void setDepartment(String department) {
		this.department = department;
	}

	@Column(name = "municipality", length = 200)
	public String getMunicipality() {
		return this.municipality;
	}

	public void setMunicipality(String municipality) {
		this.municipality = municipality;
	}

}
