package co.com.avaluo.model.entity;
// Generated 10/06/2018 05:11:29 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PropertyType generated by hbm2java
 */
@Entity
@Table(name = "property_type", schema = "avalsoft")
public class PropertyType implements java.io.Serializable {

	private int id;
	private String nameType;
	private Double tax;
	private String zone;

	public PropertyType() {
	}

	public PropertyType(int id) {
		this.id = id;
	}

	public PropertyType(int id, String nameType, Double tax, String zone) {
		this.id = id;
		this.nameType = nameType;
		this.tax = tax;
		this.zone = zone;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name_type", length = 200)
	public String getNameType() {
		return this.nameType;
	}

	public void setNameType(String nameType) {
		this.nameType = nameType;
	}

	@Column(name = "tax", precision = 17, scale = 17)
	public Double getTax() {
		return this.tax;
	}

	public void setTax(Double tax) {
		this.tax = tax;
	}

	public String getZone() {
		return zone;
	}

	public void setZone(String zone) {
		this.zone = zone;
	}

}
