package co.com.avaluo.model.entity;
// Generated 4/11/2018 09:11:06 AM by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Propietarios generated by hbm2java
 */
@Entity
@Table(name = "propietarios", schema = "avalsoft")
public class Propietarios implements java.io.Serializable {

	private int id;
	private Visitas visitas;
	private String nombre;
	private String cedula;
	private String telefono;
	private String email;
	private Double porcentaje;

	public Propietarios() {
	}

	public Propietarios(int id) {
		this.id = id;
	}

	public Propietarios(int id, Visitas visitas, String nombre, String cedula, String telefono, String email,
			Double porcentaje) {
		this.id = id;
		this.visitas = visitas;
		this.nombre = nombre;
		this.cedula = cedula;
		this.telefono = telefono;
		this.email = email;
		this.porcentaje = porcentaje;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "visitas_id")
	public Visitas getVisitas() {
		return this.visitas;
	}

	public void setVisitas(Visitas visitas) {
		this.visitas = visitas;
	}

	@Column(name = "nombre", length = 200)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "cedula", length = 20)
	public String getCedula() {
		return this.cedula;
	}

	public void setCedula(String cedula) {
		this.cedula = cedula;
	}

	@Column(name = "telefono", length = 20)
	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	@Column(name = "email", length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "porcentaje", precision = 17, scale = 17)
	public Double getPorcentaje() {
		return this.porcentaje;
	}

	public void setPorcentaje(Double porcentaje) {
		this.porcentaje = porcentaje;
	}

}
