package co.com.avaluo.model.entity;
// Generated 30/06/2018 02:39:09 PM by Hibernate Tools 5.3.0.Beta2

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Propiedad generated by hbm2java
 */
public class Propiedad implements java.io.Serializable {

	private int id;
	private Ciudad ciudad;
	private Estrato estrato;
	private Usuario usuario;
	private String tipo;
	private String registro;
	private String direccion;
	private String unidadMedida;
	private BigDecimal valorMedida;
	private Set cotizacions = new HashSet(0);

	public Propiedad() {
	}

	public Propiedad(int id, Ciudad ciudad, Estrato estrato, Usuario usuario) {
		this.id = id;
		this.ciudad = ciudad;
		this.estrato = estrato;
		this.usuario = usuario;
	}

	public Propiedad(int id, Ciudad ciudad, Estrato estrato, Usuario usuario, String tipo, String registro,
			String direccion, String unidadMedida, BigDecimal valorMedida, Set cotizacions) {
		this.id = id;
		this.ciudad = ciudad;
		this.estrato = estrato;
		this.usuario = usuario;
		this.tipo = tipo;
		this.registro = registro;
		this.direccion = direccion;
		this.unidadMedida = unidadMedida;
		this.valorMedida = valorMedida;
		this.cotizacions = cotizacions;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Ciudad getCiudad() {
		return this.ciudad;
	}

	public void setCiudad(Ciudad ciudad) {
		this.ciudad = ciudad;
	}

	public Estrato getEstrato() {
		return this.estrato;
	}

	public void setEstrato(Estrato estrato) {
		this.estrato = estrato;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public String getRegistro() {
		return this.registro;
	}

	public void setRegistro(String registro) {
		this.registro = registro;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public String getUnidadMedida() {
		return this.unidadMedida;
	}

	public void setUnidadMedida(String unidadMedida) {
		this.unidadMedida = unidadMedida;
	}

	public BigDecimal getValorMedida() {
		return this.valorMedida;
	}

	public void setValorMedida(BigDecimal valorMedida) {
		this.valorMedida = valorMedida;
	}

	public Set getCotizacions() {
		return this.cotizacions;
	}

	public void setCotizacions(Set cotizacions) {
		this.cotizacions = cotizacions;
	}

}
