package co.com.avaluo.model.entity;
// Generated 28/06/2018 07:22:07 PM by Hibernate Tools 5.3.0.Beta2

/**
 * PropertyType generated by hbm2java
 */
public class PropertyType implements java.io.Serializable {

	private int id;
	private Users users;
	private String nameType;
	private Double tax;
	private String zone;

	public PropertyType() {
	}

	public PropertyType(int id) {
		this.id = id;
	}

	public PropertyType(int id, Users users, String nameType, Double tax, String zone) {
		this.id = id;
		this.users = users;
		this.nameType = nameType;
		this.tax = tax;
		this.zone = zone;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public String getNameType() {
		return this.nameType;
	}

	public void setNameType(String nameType) {
		this.nameType = nameType;
	}

	public Double getTax() {
		return this.tax;
	}

	public void setTax(Double tax) {
		this.tax = tax;
	}

	public String getZone() {
		return this.zone;
	}

	public void setZone(String zone) {
		this.zone = zone;
	}

}
