package co.com.avaluo.model.entity;
// Generated 17/06/2018 01:24:48 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Registry generated by hbm2java
 */
@Entity
@Table(name = "registry", schema = "avalsoft")
public class Registry implements java.io.Serializable {

	private int id;
	private String idClient;
	private String name;
	private String address;
	private String phone;
	private String nameContact;
	private String phoneContact;
	private String emailContact;

	public Registry() {
	}

	public Registry(int id) {
		this.id = id;
	}

	public Registry(int id, String idClient, String name, String address, String phone, String nameContact,
			String phoneContact, String emailContact) {
		this.id = id;
		this.idClient = idClient;
		this.name = name;
		this.address = address;
		this.phone = phone;
		this.nameContact = nameContact;
		this.phoneContact = phoneContact;
		this.emailContact = emailContact;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "id_client", length = 20)
	public String getIdClient() {
		return this.idClient;
	}

	public void setIdClient(String idClient) {
		this.idClient = idClient;
	}

	@Column(name = "name", length = 300)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "address", length = 200)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "phone", length = 20)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "name_contact", length = 300)
	public String getNameContact() {
		return this.nameContact;
	}

	public void setNameContact(String nameContact) {
		this.nameContact = nameContact;
	}

	@Column(name = "phone_contact", length = 20)
	public String getPhoneContact() {
		return this.phoneContact;
	}

	public void setPhoneContact(String phoneContact) {
		this.phoneContact = phoneContact;
	}

	@Column(name = "email_contact", length = 200)
	public String getEmailContact() {
		return this.emailContact;
	}

	public void setEmailContact(String emailContact) {
		this.emailContact = emailContact;
	}

}
