package co.com.avaluo.model.entity;
// Generated 20/07/2018 10:06:20 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Reporte generated by hbm2java
 */
@Entity
@Table(name = "reporte", schema = "avalsoft")
public class Reporte implements java.io.Serializable {

	private int id;
	private Empresa empresa;
	private String codigo;
	private boolean visible;

	public Reporte() {
	}

	public Reporte(int id, Empresa empresa, String codigo, boolean visible) {
		this.id = id;
		this.empresa = empresa;
		this.codigo = codigo;
		this.visible = visible;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "empresa_id", nullable = false)
	public Empresa getEmpresa() {
		return this.empresa;
	}

	public void setEmpresa(Empresa empresa) {
		this.empresa = empresa;
	}

	@Column(name = "codigo", nullable = false, length = 150)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@Column(name = "visible", nullable = false)
	public boolean isVisible() {
		return this.visible;
	}

	public void setVisible(boolean visible) {
		this.visible = visible;
	}

}