package co.com.avaluo.model.entity;
// Generated 28/06/2018 07:22:07 PM by Hibernate Tools 5.3.0.Beta2

import java.util.HashSet;
import java.util.Set;

/**
 * Rol generated by hbm2java
 */
public class Rol implements java.io.Serializable {

	private int id;
	private String name;
	private String description;
	private boolean state;
	private Set userses = new HashSet(0);

	public Rol() {
	}

	public Rol(int id, String name, boolean state) {
		this.id = id;
		this.name = name;
		this.state = state;
	}

	public Rol(int id, String name, String description, boolean state, Set userses) {
		this.id = id;
		this.name = name;
		this.description = description;
		this.state = state;
		this.userses = userses;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public boolean isState() {
		return this.state;
	}

	public void setState(boolean state) {
		this.state = state;
	}

	public Set getUserses() {
		return this.userses;
	}

	public void setUserses(Set userses) {
		this.userses = userses;
	}

}
