package co.com.avaluo.model.entity;
// Generated 18/06/2018 08:01:50 PM by Hibernate Tools 4.0.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Rol generated by hbm2java
 */
@Entity
@Table(name = "rol", schema = "avalsoft")
public class Rol implements java.io.Serializable {

	private int id;
	private String name;
	private String description;
	private boolean state;
	private Set<Users> userses = new HashSet<Users>(0);

	public Rol() {
	}

	public Rol(int id, String name, boolean state) {
		this.id = id;
		this.name = name;
		this.state = state;
	}

	public Rol(int id, String name, String description, boolean state, Set<Users> userses) {
		this.id = id;
		this.name = name;
		this.description = description;
		this.state = state;
		this.userses = userses;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", length = 200)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "state", nullable = false)
	public boolean isState() {
		return this.state;
	}

	public void setState(boolean state) {
		this.state = state;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rol")
	public Set<Users> getUserses() {
		return this.userses;
	}

	public void setUserses(Set<Users> userses) {
		this.userses = userses;
	}

}
