package co.com.avaluo.model.entity;
// Generated 10/06/2018 05:11:29 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ServicesId generated by hbm2java
 */
@Embeddable
public class ServicesId implements java.io.Serializable {

	private int id;
	private String name;

	public ServicesId() {
	}

	public ServicesId(int id) {
		this.id = id;
	}

	public ServicesId(int id, String name) {
		this.id = id;
		this.name = name;
	}

	@Column(name = "id", nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name", length = 2000)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ServicesId))
			return false;
		ServicesId castOther = (ServicesId) other;

		return (this.getId() == castOther.getId())
				&& ((this.getName() == castOther.getName()) || (this.getName() != null && castOther.getName() != null
						&& this.getName().equals(castOther.getName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result + (getName() == null ? 0 : this.getName().hashCode());
		return result;
	}

}
