package co.com.avaluo.model.entity;
// Generated 10/06/2018 05:11:29 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Services generated by hbm2java
 */
@Entity
@Table(name = "services", schema = "avalsoft")
public class Services implements java.io.Serializable {

	private ServicesId id;

	public Services() {
	}

	public Services(ServicesId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "id", nullable = false)),
			@AttributeOverride(name = "name", column = @Column(name = "name", length = 2000)) })
	public ServicesId getId() {
		return this.id;
	}

	public void setId(ServicesId id) {
		this.id = id;
	}

}
