package co.com.avaluo.model.entity;
// Generated 10/06/2018 05:11:29 PM by Hibernate Tools 4.0.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * SoftwareAccount generated by hbm2java
 */
@Entity
@Table(name = "software_account", schema = "avalsoft")
public class SoftwareAccount implements java.io.Serializable {

	private int id;
	private String version;
	private Long download;
	private String license;
	private String country;
	private String state;
	private String city;
	private String money;
	private String language;
	private Date expirationDate;
	private Date lastDateConection;

	public SoftwareAccount() {
	}

	public SoftwareAccount(int id) {
		this.id = id;
	}

	public SoftwareAccount(int id, Long download, String license, String country, String state, String city,
			String money, String language, Date expirationDate, Date lastDateConection) {
		this.id = id;
		this.download = download;
		this.license = license;
		this.country = country;
		this.state = state;
		this.city = city;
		this.money = money;
		this.language = language;
		this.expirationDate = expirationDate;
		this.lastDateConection = lastDateConection;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	
	@Column(name = "version", length = 50)
	public String getVersion() {
		return this.version;
	}

	public void setVersion(String version) {
		this.version = version;
	}

	@Column(name = "download", precision = 15, scale = 0)
	public Long getDownload() {
		return this.download;
	}

	public void setDownload(Long download) {
		this.download = download;
	}

	@Column(name = "license", length = 50)
	public String getLicense() {
		return this.license;
	}

	public void setLicense(String license) {
		this.license = license;
	}

	@Column(name = "country", length = 200)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "state", length = 200)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "city", length = 200)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "money", length = 10)
	public String getMoney() {
		return this.money;
	}

	public void setMoney(String money) {
		this.money = money;
	}

	@Column(name = "language", length = 100)
	public String getLanguage() {
		return this.language;
	}

	public void setLanguage(String language) {
		this.language = language;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "expiration_date", length = 13)
	public Date getExpirationDate() {
		return this.expirationDate;
	}

	public void setExpirationDate(Date expirationDate) {
		this.expirationDate = expirationDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "last_date_conection", length = 13)
	public Date getLastDateConection() {
		return this.lastDateConection;
	}

	public void setLastDateConection(Date lastDateConection) {
		this.lastDateConection = lastDateConection;
	}

}
