package co.com.avaluo.model.entity;
// Generated 10/06/2018 05:11:29 PM by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tables generated by hbm2java
 */
@Entity
@Table(name = "tables", schema = "avalsoft")
public class Tables implements java.io.Serializable {

	private int id;
	private String tableType;
	private String name;
	private BigDecimal idServices;
	private String uom;
	private String uomAlt;
	private BigDecimal conver;
	private BigDecimal base;
	private Double expenses;
	private Integer dayOfJob;
	private BigDecimal minimum;
	private String law;
	private String entity;
	private String note;
	private Boolean state;
	private Integer year;
	private Set<DetailTable> detailTables = new HashSet<DetailTable>(0);

	public Tables() {
	}

	public Tables(int id) {
		this.id = id;
	}

	public Tables(int id, String tableType, String name, BigDecimal idServices, String uom, String uomAlt,
			BigDecimal conver, BigDecimal base, Double expenses, Integer dayOfJob, BigDecimal minimum, String law,
			String entity, String note, Boolean state, Integer year, Set<DetailTable> detailTables) {
		this.id = id;
		this.tableType = tableType;
		this.name = name;
		this.idServices = idServices;
		this.uom = uom;
		this.uomAlt = uomAlt;
		this.conver = conver;
		this.base = base;
		this.expenses = expenses;
		this.dayOfJob = dayOfJob;
		this.minimum = minimum;
		this.law = law;
		this.entity = entity;
		this.note = note;
		this.state = state;
		this.year = year;
		this.detailTables = detailTables;
	}

	@Id
	@GeneratedValue( strategy=GenerationType.IDENTITY)
	
	@Column(columnDefinition = "serial", name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "table_type", length = 200)
	public String getTableType() {
		return this.tableType;
	}

	public void setTableType(String tableType) {
		this.tableType = tableType;
	}

	@Column(name = "name", length = 200)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "id_services", precision = 20, scale = 0)
	public BigDecimal getIdServices() {
		return this.idServices;
	}

	public void setIdServices(BigDecimal idServices) {
		this.idServices = idServices;
	}

	@Column(name = "uom", length = 50)
	public String getUom() {
		return this.uom;
	}

	public void setUom(String uom) {
		this.uom = uom;
	}

	@Column(name = "uom_alt", length = 50)
	public String getUomAlt() {
		return this.uomAlt;
	}

	public void setUomAlt(String uomAlt) {
		this.uomAlt = uomAlt;
	}

	@Column(name = "conver", precision = 50, scale = 0)
	public BigDecimal getConver() {
		return this.conver;
	}

	public void setConver(BigDecimal conver) {
		this.conver = conver;
	}

	@Column(name = "base", precision = 50, scale = 0)
	public BigDecimal getBase() {
		return this.base;
	}

	public void setBase(BigDecimal base) {
		this.base = base;
	}

	@Column(name = "expenses", precision = 17, scale = 17)
	public Double getExpenses() {
		return this.expenses;
	}

	public void setExpenses(Double expenses) {
		this.expenses = expenses;
	}

	@Column(name = "day_of_job", precision = 5, scale = 0)
	public Integer getDayOfJob() {
		return this.dayOfJob;
	}

	public void setDayOfJob(Integer dayOfJob) {
		this.dayOfJob = dayOfJob;
	}

	@Column(name = "minimum", precision = 20, scale = 0)
	public BigDecimal getMinimum() {
		return this.minimum;
	}

	public void setMinimum(BigDecimal minimum) {
		this.minimum = minimum;
	}

	@Column(name = "law", length = 200)
	public String getLaw() {
		return this.law;
	}

	public void setLaw(String law) {
		this.law = law;
	}

	@Column(name = "entity", length = 200)
	public String getEntity() {
		return this.entity;
	}

	public void setEntity(String entity) {
		this.entity = entity;
	}

	@Column(name = "note", length = 200)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@Column(name = "state")
	public Boolean getState() {
		return this.state;
	}

	public void setState(Boolean state) {
		this.state = state;
	}

	@Column(name = "year", precision = 5, scale = 0)
	public Integer getYear() {
		return this.year;
	}

	public void setYear(Integer year) {
		this.year = year;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tables")
	public Set<DetailTable> getDetailTables() {
		return this.detailTables;
	}

	public void setDetailTables(Set<DetailTable> detailTables) {
		this.detailTables = detailTables;
	}

}
