package co.com.avaluo.model.entity;
// Generated 30/06/2018 02:39:09 PM by Hibernate Tools 5.3.0.Beta2

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario implements java.io.Serializable {

	private int id;
	private Empresa empresa;
	private Rol rol;
	private String tipoDocumento;
	private String indetificacion;
	private String nombre;
	private String correo;
	private Date fechaNacimiento;
	private String direccion;
	private String telefono;
	private String celular;
	private String contrasena;
	private boolean estado;
	private String lenguaje;
	private String profesion;
	private Set contactos = new HashSet(0);
	private Set propiedads = new HashSet(0);

	public Usuario() {
	}

	public Usuario(int id, Empresa empresa, Rol rol, boolean estado) {
		this.id = id;
		this.empresa = empresa;
		this.rol = rol;
		this.estado = estado;
	}

	public Usuario(int id, Empresa empresa, Rol rol, String tipoDocumento, String indetificacion, String nombre,
			String correo, Date fechaNacimiento, String direccion, String telefono, String celular, String contrasena,
			boolean estado, String lenguaje, String profesion, Set contactos, Set propiedads) {
		this.id = id;
		this.empresa = empresa;
		this.rol = rol;
		this.tipoDocumento = tipoDocumento;
		this.indetificacion = indetificacion;
		this.nombre = nombre;
		this.correo = correo;
		this.fechaNacimiento = fechaNacimiento;
		this.direccion = direccion;
		this.telefono = telefono;
		this.celular = celular;
		this.contrasena = contrasena;
		this.estado = estado;
		this.lenguaje = lenguaje;
		this.profesion = profesion;
		this.contactos = contactos;
		this.propiedads = propiedads;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Empresa getEmpresa() {
		return this.empresa;
	}

	public void setEmpresa(Empresa empresa) {
		this.empresa = empresa;
	}

	public Rol getRol() {
		return this.rol;
	}

	public void setRol(Rol rol) {
		this.rol = rol;
	}

	public String getTipoDocumento() {
		return this.tipoDocumento;
	}

	public void setTipoDocumento(String tipoDocumento) {
		this.tipoDocumento = tipoDocumento;
	}

	public String getIndetificacion() {
		return this.indetificacion;
	}

	public void setIndetificacion(String indetificacion) {
		this.indetificacion = indetificacion;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getCorreo() {
		return this.correo;
	}

	public void setCorreo(String correo) {
		this.correo = correo;
	}

	public Date getFechaNacimiento() {
		return this.fechaNacimiento;
	}

	public void setFechaNacimiento(Date fechaNacimiento) {
		this.fechaNacimiento = fechaNacimiento;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	public String getCelular() {
		return this.celular;
	}

	public void setCelular(String celular) {
		this.celular = celular;
	}

	public String getContrasena() {
		return this.contrasena;
	}

	public void setContrasena(String contrasena) {
		this.contrasena = contrasena;
	}

	public boolean isEstado() {
		return this.estado;
	}

	public void setEstado(boolean estado) {
		this.estado = estado;
	}

	public String getLenguaje() {
		return this.lenguaje;
	}

	public void setLenguaje(String lenguaje) {
		this.lenguaje = lenguaje;
	}

	public String getProfesion() {
		return this.profesion;
	}

	public void setProfesion(String profesion) {
		this.profesion = profesion;
	}

	public Set getContactos() {
		return this.contactos;
	}

	public void setContactos(Set contactos) {
		this.contactos = contactos;
	}

	public Set getPropiedads() {
		return this.propiedads;
	}

	public void setPropiedads(Set propiedads) {
		this.propiedads = propiedads;
	}

}
