package co.com.avaluo.model.entity;
// Generated 4/11/2018 09:11:06 AM by Hibernate Tools 4.0.1.Final

import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Visitas generated by hbm2java
 */
@Entity
@Table(name = "visitas", schema = "avalsoft")
public class Visitas implements java.io.Serializable {

	private int id;
	private Avaluos avaluos;
	private Date fechaProgramacion;
	private Usuario usuario;
	private List<Documentos> documentoses = new ArrayList<>();
	private List<Propietarios> propietarioses = new ArrayList<>();

	public Visitas() {
	}

	public Visitas(int id, Avaluos avaluos) {
		this.id = id;
		this.avaluos = avaluos;
	}

	public Visitas(int id, Avaluos avaluos, Usuario usuario, Date fechaProgramacion, List<Documentos> documentoses, List<Propietarios> propietarioses) {
		this.id = id;
		this.avaluos = avaluos;
		this.usuario = usuario;
		this.fechaProgramacion = fechaProgramacion;
		this.documentoses = documentoses;
		this.propietarioses = propietarioses;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "avaluos_id", nullable = false)
	public Avaluos getAvaluos() {
		return this.avaluos;
	}

	public void setAvaluos(Avaluos avaluos) {
		this.avaluos = avaluos;
	}

	@Column(name = "fecha_programacion", length = 13)
	public Date getFechaProgramacion() {
		return this.fechaProgramacion;
	}

	public void setFechaProgramacion(Date fechaProgramacion) {
		this.fechaProgramacion = fechaProgramacion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "avaluador_id")
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "visitas")
	public List<Documentos> getDocumentoses() {
		return this.documentoses;
	}

	public void setDocumentoses(List<Documentos> documentoses) {
		this.documentoses = documentoses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "visitas")
	public List<Propietarios> getPropietarioses() {
		return this.propietarioses;
	}

	public void setPropietarioses(List<Propietarios> propietarioses) {
		this.propietarioses = propietarioses;
	}

}
